(function () {
  "use strict";

  const data = {
    meta: {
      title: "宏观资产方向跟踪",
      englishTitle: "MACRO / VIEW LEDGER",
      baselineDate: "2026-09-01",
      latestSourceDate: "2026-09-07",
      posture: "防守中看分化：半导体修复，软件与农业休整",
      postureNote: "长端利率压力未解除；关注半导体硬件盈利与能源的相对确定性、银行H股资本重估，软件及部分农业板块短期谨慎。粮食安全中长期观点沿用，未被本篇否定。",
      disclaimer: "本页面为Brassivo Research对公开宏观资料的二次整理，不代表原作者，不构成投资建议，也不包含实时行情。"
    },
    rotation: [
      {id: "precious", label: "黄金白银", stage: "已启动", state: "passed", note: "反弹目标已到，短期止盈控仓"},
      {id: "industrial", label: "有色工业", stage: "已轮动", state: "passed", note: "等待下一次趋势确认"},
      {id: "energy", label: "能源", stage: "后段", state: "passed", note: "地缘冲突与低战略储备支撑油价，仍不追涨"},
      {id: "agriculture", label: "粮食安全", stage: "结构主线", state: "current", note: "中长期供需逻辑沿用；9月7日提示部分农业板块大幅修复后短期休整"}
    ],
    assets: [
      {
        id: "global-risk",
        asset: "全球风险资产",
        category: "总资产",
        horizon: "短期",
        direction: "结构性谨慎 / 去久期与贝塔",
        tone: "caution",
        action: "维持结构性防守（沿用）；结合本文推导，区分半导体硬件和能源的相对机会，不把金融体系托底等同于全面风险解除。",
        evidence: "原文明确 + 基于原文推导",
        status: "有效",
        rationale: "文章指出股权风险溢价尚未重建，长端利率继续上行时权益缓冲薄弱；财政注资可加固中国金融体系，却无法完全抵御全球流动性重新定价。",
        trigger: "油价和长端收益率同步回落，成长板块市场宽度改善，或回调后风险收益比明显修复。",
        updated: "2026-09-07",
        sourceRefs: ["S1", "S3", "S4", "S5", "20260902-S1", "20260902-S2", "20260907-S1"],
        priority: true
      },
      {
        id: "us-equity",
        asset: "美股",
        category: "股票",
        horizon: "短期",
        direction: "谨慎偏空，不直接做空",
        tone: "caution",
        action: "维持总体谨慎（沿用），分开跟踪半导体支撑位修复与软件阻力位风险；不由局部修复推导美股全面转多。",
        evidence: "原文明确 + 基于原文推导",
        status: "有效",
        rationale: "文章继续警惕长久期成长估值与薄弱的股权风险溢价，同时明确区分半导体硬件修复机会和软件板块休整风险。",
        trigger: "企业盈利继续上修且长端收益率回落，或政策明显转鸽，谨慎判断弱化。",
        updated: "2026-09-07",
        sourceRefs: ["S1", "S5", "20260902-S2", "20260907-S1"],
        priority: true
      },
      {
        id: "hong-kong-equity",
        asset: "港股 / 高估值成长",
        category: "股票",
        horizon: "短期",
        direction: "谨慎偏空 / 去拥挤与贝塔",
        tone: "caution",
        action: "不急于抄底，降低高估值成长敞口；跟踪美元、长债收益率和美股期货。",
        evidence: "原文明确 + 基于原文推导",
        status: "有效",
        rationale: "恒指在大型权重支撑下接近收平，但二线AI和券商继续下跌；指数表面分化来自成分权重，不代表底层风险逻辑分叉。",
        trigger: "长端收益率回落，二线成长止跌且港股市场宽度改善。",
        updated: "2026-09-02",
        sourceRefs: ["S4", "20260902-S1"],
        priority: true
      },
      {
        id: "a-share-duration",
        asset: "A股高久期成长 / 科创",
        category: "股票",
        horizon: "短期",
        direction: "承压 / 降低拥挤敞口",
        tone: "negative",
        action: "降低电子、半导体、通信、计算机和传媒等拥挤成长敞口；不把结构性下跌扩大为全市场看空。",
        evidence: "原文明确 + 行情观察",
        status: "有效",
        rationale: "创业板和科创50领跌，五个成长板块主力资金合计净流出约400亿元；上证50相对抗跌，资金转向国防军工和电网设备。",
        trigger: "长端收益率与油价回落，成长板块资金流和市场宽度连续改善。",
        updated: "2026-09-02",
        sourceRefs: ["20260902-S1"],
        priority: true
      },
      {
        id: "us-ai-earnings",
        asset: "美股 / AI盈利",
        category: "股票",
        horizon: "中期",
        direction: "基本面仍有支撑",
        tone: "positive",
        action: "不因实际利率上升机械清仓；重点跟踪盈利兑现。",
        evidence: "原文明确",
        status: "有效",
        rationale: "AI驱动的盈利增长预期可部分抵消长端利率上升带来的估值压缩；文章同时提醒长久期成长股的内嵌估值风险。",
        trigger: "盈利预期下修，或实际利率继续上升且估值不降，将削弱支撑。",
        updated: "2026-09-07",
        sourceRefs: ["S1", "20260907-S1"],
        priority: false
      },
      {
        id: "precious-long",
        asset: "黄金、白银",
        category: "商品",
        horizon: "长期",
        direction: "看多",
        tone: "positive",
        action: "核心配置逻辑不变；持有为主。",
        evidence: "原文明确",
        status: "有效",
        rationale: "纪要明确指出黄金、白银及大宗商品的长期逻辑没有改变。",
        trigger: "需要后续资料明确否定长期逻辑，才改变长期方向。",
        updated: "2026-08-31",
        sourceRefs: ["S3"],
        priority: true
      },
      {
        id: "precious-short",
        asset: "贵金属及矿业股",
        category: "商品",
        horizon: "短期",
        direction: "止盈 / 控仓",
        tone: "caution",
        action: "反弹目标附近获利了结，控制风险和仓位；新增仓位等待波动释放。",
        evidence: "原文明确",
        status: "有效",
        rationale: "黄金从约4800目标区回落至约4300，白银回落至约63并连续下跌三日；金银未按地缘避险逻辑上涨，短期风险信号得到确认。",
        trigger: "价格完成去杠杆、长端收益率回落且资金重新流入，或新资料重新确认加仓信号。",
        updated: "2026-09-02",
        sourceRefs: ["S3", "S4", "S5", "20260902-S1", "20260902-S2"],
        priority: true
      },
      {
        id: "commodities",
        asset: "大宗商品整体",
        category: "商品",
        horizon: "中长期",
        direction: "看多，但内部分化",
        tone: "positive",
        action: "保留商品方向，从已大涨品种转向下一棒，避免平均追涨。",
        evidence: "原文明确",
        status: "有效",
        rationale: "商品长期逻辑未变，但强美元和长端利率压制贵金属，地缘冲突推升原油，粮食安全获得实体供需支撑。",
        trigger: "若轮动顺序被价格和新资料证伪，重新定位阶段。",
        updated: "2026-09-01",
        sourceRefs: ["S3", "S4", "S5"],
        priority: true
      },
      {
        id: "agriculture",
        asset: "农产品",
        category: "商品",
        horizon: "中长期",
        direction: "看多 / 独立结构主线",
        tone: "positive",
        action: "保留粮食安全中长期结构方向；种业由涨停转跌停后不接短期拥挤交易，等待波动和筹码消化。",
        evidence: "原文明确 + 行情观察",
        status: "有效",
        rationale: "全球玉米库存消费比降至17.9%的警戒区间，欧洲减产扩大供给缺口，粮食产业链出现广泛价格与资金确认。",
        trigger: "若库存消费比持续回升、供给缺口修复且相对收益趋势持续转弱，再下调中长期方向；单日跌停不单独构成反转。",
        updated: "2026-09-02",
        sourceRefs: ["S3", "S4", "20260902-S1"],
        priority: true
      },
      {
        id: "industrial-metals",
        asset: "有色工业金属",
        category: "商品",
        horizon: "中期",
        direction: "主要轮动已过",
        tone: "neutral",
        action: "继续持有观察，不把单日反弹当成新起点。",
        evidence: "原文明确 + 基于原文推导",
        status: "有效",
        rationale: "在轮动顺序中位于贵金属之后、能源和农产品之前。",
        trigger: "若重新出现有色领涨并获原文确认，再上调方向。",
        updated: "2026-08-31",
        sourceRefs: ["S3"],
        priority: false
      },
      {
        id: "energy",
        asset: "能源 / 原油",
        category: "商品",
        horizon: "中期",
        direction: "事件驱动偏强 / 相对受益",
        tone: "positive",
        action: "沿用不追涨纪律，关注能源盈利的相对确定性；不把利率相关性当作独立买入指令。",
        evidence: "原文明确 + 基于原文推导",
        status: "有效",
        rationale: "文章认为中东能源冲击共同推升通胀预期、长债收益率和能源企业盈利，能源具有油价高位带来的相对确定性。",
        trigger: "冲突降级、供给恢复或油价回落将削弱相对优势；若非事件性趋势延续，再评估是否升级为独立主线。",
        updated: "2026-09-07",
        sourceRefs: ["S3", "S4", "S5", "20260902-S1", "20260902-S2", "20260907-S1"],
        priority: false
      },
      {
        id: "usd",
        asset: "美元",
        category: "货币",
        horizon: "短期",
        direction: "偏强",
        tone: "positive",
        action: "作为防御信号观察，不升级为长期看多。",
        evidence: "行情观察 + 基于原文推导",
        status: "观察中",
        rationale: "鹰派政策预期持续推动美元走强，并压制港股、贵金属和高估值成长资产。",
        trigger: "通胀回落、政策转鸽或美元重新转弱。",
        updated: "2026-09-01",
        sourceRefs: ["S1", "S3", "S4", "S5"],
        priority: false
      },
      {
        id: "long-ust",
        asset: "美国长久期国债",
        category: "债券",
        horizon: "短中期",
        direction: "价格继续承压 / 收益率上行",
        tone: "negative",
        action: "暂不激进加久期；等待政策与通胀路径明确。",
        evidence: "基于原文推导",
        status: "观察中",
        rationale: "文中10年期、30年期美债收益率分别为4.78%和5.25%；财政赤字、AI资本开支融资需求及主要买家需求下滑构成长端上行压力。数值仅为9月7日原文快照。",
        trigger: "长端收益率趋势转为下行，财政融资和债券需求压力缓和，或通胀与能源冲击消退（跟踪条件属推导）。",
        updated: "2026-09-07",
        sourceRefs: ["S1", "S4", "S5", "20260902-S1", "20260902-S2", "20260907-S1"],
        priority: true
      },
      {
        id: "jpy",
        asset: "日元",
        category: "货币",
        horizon: "短期",
        direction: "对美元偏弱",
        tone: "negative",
        action: "仅作跨市场风险信号，不作为独立配置结论。",
        evidence: "行情观察",
        status: "观察中",
        rationale: "美元兑日元一度突破160，反映鹰派冲击外溢。",
        trigger: "日本加息预期显著升温或美元转弱。",
        updated: "2026-08-31",
        sourceRefs: ["S1"],
        priority: false
      },
      {
        id: "jgb",
        asset: "日本国债",
        category: "债券",
        horizon: "短期",
        direction: "价格承压 / 收益率偏升",
        tone: "negative",
        action: "只记录外溢风险，暂无明确交易动作。",
        evidence: "行情观察",
        status: "观察中",
        rationale: "30年期日债收益率升破3%，为1996年以来高位，全球长久期债券同步承压。",
        trigger: "加息预期回落或收益率趋势反转。",
        updated: "2026-09-02",
        sourceRefs: ["S1", "20260902-S2"],
        priority: false
      },
      {
        category: "股票",
        status: "有效",
        id: "us-semiconductors",
        asset: "美国半导体硬件 / 费城半导体",
        horizon: "短期",
        direction: "偏多 / 支撑位修复候选",
        tone: "positive",
        action: "关注支撑位能否守住及盈利兑现，等待修复确认；原文未给入场价或仓位。",
        evidence: "原文明确 + 基于原文推导",
        rationale: "正文指向半导体硬件短期盈利确定性，图一明确称费城半导体运行到支持位置、应该有所修复；等待确认的执行纪律为推导。",
        trigger: "支撑失守或盈利预期下修则候选失效；价格止跌并形成修复才增强判断（条件为推导）。",
        priority: true,
        updated: "2026-09-07",
        sourceRefs: ["20260907-S1"]
      },
      {
        category: "股票",
        status: "有效",
        id: "us-software",
        asset: "美国软件板块",
        horizon: "短期",
        direction: "谨慎 / 阻力位休整",
        tone: "caution",
        action: "暂停追涨，等待阻力位消化及后续确认；不据此直接做空（执行方式为推导）。",
        evidence: "原文明确 + 基于原文推导",
        rationale: "正文认为软件业在过去三个月大幅修复后可能需要休养生息，图二明确标示美国软件业指数运行到阻力位。",
        trigger: "有效突破并站稳阻力位、盈利预期同步改善，则休整判断弱化（条件为推导）。",
        priority: true,
        updated: "2026-09-07",
        sourceRefs: ["20260907-S1"]
      },
      {
        category: "商品",
        status: "有效",
        id: "agriculture-short",
        asset: "部分农业板块",
        horizon: "短期",
        direction: "谨慎 / 修复后休整",
        tone: "caution",
        action: "不追逐此前三个月大幅修复的农业板块，等待休整；不将此判断扩大为全部农产品长期看空。",
        evidence: "原文明确 + 基于原文推导",
        rationale: "文章结尾提示一些农业板块在过去三个月大幅修复后可能需要休养生息；图三展示小麦与半导体负相关，不构成独立买卖规则。",
        trigger: "休整后相对强度和供需重新确认，或后续文章明确转向（条件为推导）。",
        priority: true,
        updated: "2026-09-07",
        sourceRefs: ["20260907-S1"]
      },
      {
        category: "股票",
        status: "有效",
        id: "china-bank-h",
        asset: "中国银行H股 / 红利",
        horizon: "中期",
        direction: "偏多 / 资本重估，盈利受限",
        tone: "positive",
        action: "跟踪注资落实、H股折价及分红支撑；不把资本补充当成盈利模式已修复，也不追逐已明显拉升的价格（动作属推导）。",
        evidence: "原文明确 + 基于原文推导",
        rationale: "文章重申此前对银行及红利板块的推荐，认为银行H股重估体现资本充足率改善和折价收窄；同时指出定增摊薄、净息差收缩和内生盈利不足尚未解决。",
        trigger: "注资不及预期、摊薄或息差压力超过资本改善收益，或折价安全边际消失，则重新评估（条件为推导）。",
        priority: true,
        updated: "2026-09-07",
        sourceRefs: ["20260907-S1"]
      },
      {
        category: "股票",
        status: "观察中",
        id: "western-financials",
        asset: "美国 / 西方金融板块",
        horizon: "中期",
        direction: "中性 / 息差改善对冲债券损失",
        tone: "neutral",
        action: "仅观察收益率曲线、净息差与债券组合损失，不升级为明确买入指令。",
        evidence: "原文明确 + 基于原文推导",
        rationale: "文章称西方金融板块对长端利率上行的敏感度接近中性，曲线趋陡带来的息差扩张部分抵消债券浮亏；美国金融亦受益于短端利率上行带来的息差改善。",
        trigger: "息差收益无法抵消债券损失，或曲线及短端利率变化逆转（条件为推导）。",
        priority: false,
        updated: "2026-09-07",
        sourceRefs: ["20260907-S1"]
      },
      {
        category: "总资产",
        status: "观察中",
        id: "em-external-risk",
        asset: "新兴市场资产 / 外部融资",
        horizon: "短期",
        direction: "谨慎 / 外部压力测试",
        tone: "caution",
        action: "仅跟踪资本流动、本币与融资条件；不由条件性风险直接生成做空动作。",
        evidence: "原文明确 + 基于原文推导",
        rationale: "文章警惕美债收益率急升带来的资本外流、本币承压和金融条件收紧，点名马来西亚、智利及墨西哥对日本资金回流较脆弱。",
        trigger: "若日元进一步升值至美元兑日元约151且长端利率压力深化，风险加大；反向变化则缓和。151是原文条件情景，并非当前报价。",
        priority: false,
        updated: "2026-09-07",
        sourceRefs: ["20260907-S1"]
      }
    ],
    observations: [
      {market: "中国银行H股与A股", observation: "文中称3月5日以来六家银行H股均跑赢对应A股及恒指，H股涨幅12.5%至35.7%，同期恒指约1.3%。", handling: "仅作为原文历史区间表现，非实时收益率；资本重估与定增摊薄分开跟踪。"},
      {market: "美国国债收益率", observation: "9月7日原文快照：2年期4.37%、10年期4.78%、30年期5.25%。", handling: "不把10年期较上篇小幅回落解读为趋势反转；文中仍判断长端存在上行惯性。"},
      {market: "半导体与软件", observation: "图一：费城半导体到支持位；图二：美国软件业指数到阻力位。", handling: "分别登记底部、顶部候选；未给出可可靠辨读的数值价位，不补写目标价。"},
      {market: "农业与半导体", observation: "图三展示小麦与半导体负相关，正文提示部分农业板块大幅修复后休整。", handling: "相关性不构成轮动交易规则；短期农业谨慎与中长期粮食安全逻辑分开。"},
      {market: "日元与新兴市场", observation: "文中提出日元进一步升值至约151的条件情景，并提示新兴市场对日本资金回流的脆弱性。", handling: "不将条件情景写成现价或独立日元做多信号；旧日元方向保留原日期。"},
      {market: "恒生科技", observation: "图四展示恒生科技指数走势，未明确提出新的买入指令。", handling: "不凭图形自行新增底部信号，港股成长沿用原方向与日期。"}
    ],
    changes: [
      {date: "2026-09-07", asset: "美国半导体硬件 / 费城半导体", from: "美股总体谨慎，未单列修复机会", to: "偏多 / 支撑位修复候选", reason: "正文指向半导体硬件短期盈利确定性，图一明确称费城半导体运行到支持位置、应该有所修复；等待确认的执行纪律为推导。", turningPoint: {side: "bottom", label: "底部候选", priceContext: "9月7日图一明确指出费城半导体到达支持位置、应该有所修复；由总体谨慎中单列短期修复方向，反转尚待确认，未读取无法辨认的具体价位。"}, sources: ["20260907-S1"]},
      {date: "2026-09-07", asset: "美国软件板块", from: "未单列", to: "谨慎 / 阻力位休整", reason: "正文认为软件业在过去三个月大幅修复后可能需要休养生息，图二明确标示美国软件业指数运行到阻力位。", turningPoint: {side: "top", label: "顶部候选", priceContext: "9月7日图二明确指出美国软件业指数到达阻力位；结合过去三个月大幅修复后的休整判断，标为顶部候选，尚非下跌确认。"}, sources: ["20260907-S1"]},
      {date: "2026-09-07", asset: "部分农业板块", from: "中长期看多，短期拥挤风险", to: "谨慎 / 修复后休整", reason: "文章结尾提示一些农业板块在过去三个月大幅修复后可能需要休养生息；图三展示小麦与半导体负相关，不构成独立买卖规则。", turningPoint: null, sources: ["20260907-S1"]},
      {date: "2026-09-07", asset: "中国银行H股 / 红利", from: "未单列", to: "偏多 / 资本重估，盈利受限", reason: "文章重申此前对银行及红利板块的推荐，认为银行H股重估体现资本充足率改善和折价收窄；同时指出定增摊薄、净息差收缩和内生盈利不足尚未解决。", turningPoint: null, sources: ["20260907-S1"]},
      {date: "2026-09-07", asset: "美国 / 西方金融板块", from: "未单列", to: "中性 / 息差改善对冲债券损失", reason: "文章称西方金融板块对长端利率上行的敏感度接近中性，曲线趋陡带来的息差扩张部分抵消债券浮亏；美国金融亦受益于短端利率上行带来的息差改善。", turningPoint: null, sources: ["20260907-S1"]},
      {date: "2026-09-07", asset: "新兴市场资产 / 外部融资", from: "未单列", to: "谨慎 / 外部压力测试", reason: "文章警惕美债收益率急升带来的资本外流、本币承压和金融条件收紧，点名马来西亚、智利及墨西哥对日本资金回流较脆弱。", turningPoint: null, sources: ["20260907-S1"]},
      {date: "2026-09-02", asset: "A股高久期成长 / 科创", from: "未单列", to: "承压 / 降低拥挤敞口", reason: "创业板、科创50和五个成长板块同步承压，资金转向低久期价值与防御方向。", turningPoint: null, sources: ["20260902-S1"]},
      {date: "2026-09-02", asset: "能源 / 原油", from: "事件驱动偏强 / 不追涨", to: "事件驱动偏强 / 相对受益", reason: "油价升至90至95美元区间，低战略储备放大供给冲击，能源成为风险资产中的相对例外。", turningPoint: null, sources: ["20260902-S1", "20260902-S2"]},
      {date: "2026-09-02", asset: "全球风险资产", from: "中性偏谨慎", to: "结构性谨慎 / 去久期与贝塔", reason: "金银未按避险逻辑上涨，确认市场交易的是滞胀式利率冲击；受压集中在久期、拥挤度和贝塔。", turningPoint: null, sources: ["20260902-S1", "20260902-S2"]},
      {date: "2026-09-01", asset: "农产品 / 粮食安全", from: "商品轮动下一棒、重点观察", to: "独立结构性交易主线", reason: "库存消费比进入警戒区、欧洲减产扩大供给缺口，产业链价格和资金形成确认。", turningPoint: null, sources: ["S4"]},
      {date: "2026-09-01", asset: "贵金属及矿业股", from: "短期谨慎、不追高", to: "反弹目标到位，止盈控仓", reason: "黄金反弹至目标区，矿股先行承压后COMEX金银继续回落。", turningPoint: {side: "top", label: "顶部候选", priceContext: "黄金反弹至目标区，矿股先行承压，随后COMEX金银开始回落；方向反转尚未完全走出。"}, sources: ["S4", "S5"]},
      {date: "2026-09-01", asset: "港股 / 高估值成长", from: "无独立方向", to: "短期谨慎偏空", reason: "强美元、长端收益率上行和隔夜美股走弱触发补跌。", turningPoint: null, sources: ["S4"]},
      {date: "2026-09-01", asset: "全球风险资产", from: "短期谨慎", to: "维持防守，风险继续升温", reason: "地缘油价冲击、长端利率上行与九月调整窗口叠加。", turningPoint: null, sources: ["S4", "S5"]},
      {date: "2026-08-31", asset: "全部", from: "无（首次建账）", to: "建立基线", reason: "以8-31文件夹内首批资料建立初始方向。", turningPoint: null, sources: ["S1", "S2", "S3"]}
    ],
    sources: [
      {
        id: "S1",
        date: "2026-08-31",
        title: "市场将如何定价沃什和贝森特的巅峰对决",
        type: "完整文章",
        role: "政策分歧、风险资产仓位、美股、实际利率和长端美债判断"
      },
      {
        id: "S2",
        date: "2026-08-31",
        title: "文章长截图",
        type: "重复资料",
        role: "与S1内容重复，用于视觉核对，不作为独立证据"
      },
      {
        id: "S3",
        date: "2026-08-31",
        title: "新神雕侠侣：沃什 vs 贝森特",
        type: "当日纪要",
        role: "防御交易变化、贵金属风险、商品长期逻辑及农产品轮动"
      },
      {
        id: "S4",
        date: "2026-09-01",
        title: "每日复盘与展望：A股粮食涨停潮，港股开门黑",
        type: "当日复盘摘要",
        role: "粮食安全结构主线、A股板块轮动、港股补跌、美元和长端利率"
      },
      {
        id: "S5",
        date: "2026-09-01",
        title: "地缘冲突、贵金属风险与九月调整窗口",
        type: "评论摘要",
        role: "油价冲击、贵金属止盈、长端利率与周期调整窗口"
      },
      {
        id: "20260902-S1",
        date: "2026-09-02",
        title: "全球债市暴熊，全球股市承压",
        type: "当日复盘摘要",
        role: "滞胀式利率冲击、A股成长去拥挤、港股权重分化、能源与粮食安全短期表现"
      },
      {
        id: "20260902-S2",
        date: "2026-09-02",
        title: "全球债市冲击与周线趋势窗口",
        type: "评论摘要",
        role: "全球长债收益率、跨境套利阻滞、贵金属回落、油价和周线趋势转换窗口"
      },
      {
        id: "20260907-S1",
        date: "2026-09-07",
        title: "财政买入金融，市场买入什么？",
        type: "完整文章（图像PDF，已视觉核对）",
        role: "中国银行资本重估与盈利限制、长端利率风险、半导体支撑位修复、软件阻力位及部分农业短期休整"
      }
    ]
  };

  if (typeof window !== "undefined") {
    window.HONG_HAO_DASHBOARD_DATA = Object.freeze(data);
  }
})();
