import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const html=fs.readFileSync(new URL('../block-kart/index.html',import.meta.url),'utf8');
test('shield blocks one attack; ice scores only one effective hit and slows victim',()=>{const scope={Math,G:{},toast(){},emit(){},sfx(){},flash(){}};vm.createContext(scope);vm.runInContext(html.slice(html.indexOf('function hitKart(k,owner,ice=false)'),html.indexOf('function aiInput(k, dt, autoItems=true)')),scope);scope.attacker={hits:0};scope.victim={shieldT:8,spinT:0,speed:30};vm.runInContext('hitKart(victim,attacker,true)',scope);assert.equal(scope.attacker.hits,0);assert.equal(scope.victim.shieldT,0);assert.equal(scope.victim.freezeT,undefined);vm.runInContext('hitKart(victim,attacker,true)',scope);assert.equal(scope.attacker.hits,1);assert.equal(scope.victim.freezeT,3);vm.runInContext('hitKart(victim,attacker,true)',scope);assert.equal(scope.attacker.hits,1);});
test('all eight types are equally likely at every rank, with no rocket',()=>{const scope={ITEM_NAMES:{jelly:'果冻',missile:'追踪',shield:'护盾',lightning:'闪电',ice:'冰冻',spring:'弹簧',giant:'巨型',smoke:'笑脸'},G:{karts:Array(6)},Math:Object.create(Math)};vm.createContext(scope);vm.runInContext(html.slice(html.indexOf('function pickItem(rank)'),html.indexOf('async function saveCloudScore')),scope);const found=new Set();for(let i=0;i<1000;i++){scope.Math.random=()=>i/1000;found.add(vm.runInContext('pickItem(3)',scope));}assert.deepEqual([...found].sort(),['giant','ice','jelly','lightning','missile','shield','smoke','spring']);});
test('spring and giant activate independently; smoke respects range and shields without scoring knockdowns',()=>{
 const scope={Math,G:{karts:[]},toast(){},emit(){},sfx(){},heldItems:k=>[k.item,...k.itemQueue],setItems(k,items){k.item=items[0];k.itemQueue=items.slice(1);}};vm.createContext(scope);
 vm.runInContext(html.slice(html.indexOf('function useItem(k,index=0)'),html.indexOf('function hitKart(k,owner,ice=false)')),scope);
 scope.k={item:'spring',itemQueue:['giant','smoke'],vy:0,boostT:0,heading:0,x:0,z:0,y:0,isPlayer:true,hits:0};scope.near={x:5,z:0,y:0,shieldT:0};scope.shielded={x:8,z:0,y:0,shieldT:8};scope.far={x:30,z:0,y:0};scope.G.karts=[scope.k,scope.near,scope.shielded,scope.far];
 vm.runInContext('useItem(k,0)',scope);assert.equal(scope.k.vy,12);assert.equal(scope.k.boostT,0);assert.deepEqual(scope.k.itemQueue,['giant','smoke']);
 vm.runInContext('useItem(k,1)',scope);assert.equal(scope.k.giantT,6);assert.equal(scope.k.itemQueue[0],null);
 vm.runInContext('useItem(k,2)',scope);assert.equal(scope.near.smokeT,3);assert.equal(scope.shielded.shieldT,0);assert.equal(scope.shielded.smokeT,undefined);assert.equal(scope.far.smokeT,undefined);assert.equal(scope.k.hits,0);assert.equal(scope.k.smokeT,undefined);
});

test('equal-probability equipment generation does not depend on race position',()=>{const scope={ITEM_NAMES:{jelly:'果冻',missile:'追踪',shield:'护盾',lightning:'闪电',ice:'冰冻',spring:'弹簧',giant:'巨型',smoke:'笑脸'},Math:Object.create(Math)};vm.createContext(scope);vm.runInContext(html.slice(html.indexOf('function pickItem(rank)'),html.indexOf('async function saveCloudScore')),scope);for(const rank of [0,3,5]){const counts={};for(let i=0;i<800;i++){scope.Math.random=()=>i/800;scope.rank=rank;const item=vm.runInContext('pickItem(rank)',scope);counts[item]=(counts[item]||0)+1;}assert.deepEqual(Object.values(counts),Array(8).fill(100));}});
test('giant collision respects shielding and only scores each opponent once per activation; spring clears ground traps',()=>{
 const scope={Math,G:{study:true,tr:{N:100}},world:{boxes:[],pads:[],jellies:[],missiles:[],group:{remove(){}}},toast(){},emit(){},sfx(){},flash(){}};vm.createContext(scope);
 vm.runInContext(html.slice(html.indexOf('function hitKart(k,owner,ice=false)'),html.indexOf('function aiInput(k, dt, autoItems=true)'))+html.slice(html.indexOf('function interactions(dt)'),html.indexOf('function computeOrder()',html.indexOf('function interactions(dt)'))),scope);
 const kart=(x)=>({x,z:0,y:0,speed:30,spinT:0,ch:{w:1},hits:0,shieldT:0});scope.a=kart(0);scope.a.giantT=6;scope.b=kart(3);scope.G.karts=[scope.a,scope.b];vm.runInContext('interactions(.01)',scope);assert.equal(scope.a.hits,1);scope.b.spinT=0;scope.b.x=3;vm.runInContext('interactions(.01)',scope);assert.equal(scope.a.hits,1);
 scope.a=kart(0);scope.a.giantT=6;scope.b=kart(3);scope.b.shieldT=8;scope.G.karts=[scope.a,scope.b];vm.runInContext('interactions(.01)',scope);assert.equal(scope.b.shieldT,0);assert.equal(scope.a.hits,0);scope.b.x=3;vm.runInContext('interactions(.01)',scope);assert.equal(scope.a.hits,0);
 scope.a=kart(0);scope.a.y=2;scope.G.karts=[scope.a];const trap={x:0,z:0,arm:0,m:{rotation:{y:0}},owner:{hits:0}};scope.world.jellies=[trap];vm.runInContext('interactions(.01)',scope);assert.equal(scope.a.spinT,0);assert.equal(scope.world.jellies.length,1);scope.a.y=0;vm.runInContext('interactions(.01)',scope);assert(scope.a.spinT>0);assert.equal(scope.world.jellies.length,0);
});
