import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function setup(){let now=1000;const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};const scope={localStorage:storage};vm.createContext(scope);vm.runInContext(fs.readFileSync(new URL('../block-kart/play-limit.js',import.meta.url),'utf8'),scope);return {storage,create:(verify)=>scope.KartPlayLimitFactory(storage,()=>now,verify),advance:ms=>now+=ms};}
test('30 minutes locks for 30 minutes; refresh and idle time preserve the deadline',()=>{const s=setup();let timer=s.create();s.advance(15*60000);assert(!timer.tick(true).locked);timer=s.create();s.advance(15*60000);assert(timer.tick(true).locked);timer=s.create();s.advance(29*60000);assert(timer.tick(false).locked);s.advance(60000);assert(!timer.tick(false).locked);s.advance(30*60000);assert(timer.tick(true).locked);});
test('menus and closed time do not count, and concurrent tabs do not double count',()=>{const s=setup();const a=s.create(),b=s.create();s.advance(20*60000);a.tick(false);b.tick(false);s.advance(15*60000);assert.equal(a.tick(true).used,15*60000);assert.equal(b.tick(true).used,15*60000);s.advance(60*60000);const c=s.create();assert.equal(c.tick(true).used,15*60000);});

test('wrong password preserves rest; valid administrator unlock resets time across tabs and refresh',async()=>{const s=setup(),a=s.create(async pin=>pin==='test-valid'),b=s.create();s.advance(30*60000);assert(a.tick(true).locked);const before=a.tick(false).remaining;assert.equal(await a.unlock('wrong'),false);assert.equal(a.tick(false).remaining,before);assert.equal(await a.unlock('test-valid'),true);assert.equal(a.tick(true).used,0);assert.equal(b.tick(true).used,0);assert.equal(s.create().tick(false).locked,false);s.advance(29*60000);assert.equal(a.tick(true).locked,false);s.advance(60000);assert.equal(a.tick(true).locked,true);});
test('administrator unlock cannot reset accumulated time before a rest lock',async()=>{const s=setup(),a=s.create(async()=>true);s.advance(10*60000);a.tick(true);assert.equal(await a.unlock('test-valid'),false);assert.equal(a.tick(false).used,10*60000);});

test('failed persistence never reports a successful unlock or clears the existing lock',async()=>{const s=setup(),a=s.create(async()=>true);s.advance(30*60000);assert(a.tick(true).locked);s.storage.setItem=()=>{throw Error('storage unavailable');};await assert.rejects(a.unlock('test-valid'),/storage unavailable/);assert.equal(a.tick(false).locked,true);});
