import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function setup(rec){const node=()=>({children:[],textContent:'',style:{},classList:{toggle(){}},setAttribute(){},append(...x){this.children.push(...x);}});const timers=new Map();let next=0;const root={document:{createElement:node},SpeechRecognition:rec,setTimeout(fn,ms){timers.set(++next,{fn,ms});return next;},clearTimeout(id){timers.delete(id);}};root.globalThis=root;vm.createContext(root);vm.runInContext(fs.readFileSync(new URL('../block-kart/english-training.js',import.meta.url),'utf8'),root);return {root,box:node(),timers};}
const q={answer:'apple',meaning:'苹果',options:['apple','pear','cat','dog'],practiceType:'spell'};
test('spelling normalizes case and whitespace; incorrect text is not converted into the correct answer',()=>{const {root,box}=setup();let got;root.KartEnglishTraining.mount(box,q,x=>got=x);const form=box.children[0],input=form.children[0];input.value=' Apple ';form.onsubmit({preventDefault(){}});assert.equal(got,'apple');assert.equal(input.disabled,true);});
test('recognition only accepts an exact normalized target among alternatives and late results are ignored',()=>{let rec;class Recognition{constructor(){rec=this;}start(){}abort(){}}const {root,box}=setup(Recognition);let got;root.KartEnglishTraining.mount(box,{...q,practiceType:'read'},x=>got=x);box.children[1].onclick();assert.equal(rec.lang,'en-US');rec.onresult({results:[[{transcript:'pear'},{transcript:'Apple.'}]]});assert.equal(got,'apple');root.KartEnglishTraining.stop();rec.onresult({results:[[{transcript:'dog'}]]});assert.equal(got,'apple');});
test('unsupported speech disables microphone while keeping spelling fallback',()=>{const {root,box}=setup();root.KartEnglishTraining.mount(box,{...q,practiceType:'read'},()=>{});assert.equal(box.children[1].disabled,true);assert(box.children.some(x=>x.textContent==='改用拼写作答'));});

test('throwing synthesis cancel cannot prevent submitting an answer or closing a quiz',()=>{const {root,box}=setup();root.speechSynthesis={cancel(){throw Error('speech service offline');}};let got;root.KartEnglishTraining.mount(box,{...q,practiceType:'translate'},x=>got=x);box.children[0].onclick();assert.equal(got,'apple');assert.doesNotThrow(()=>root.KartEnglishTraining.stop());});
test('unresponsive playback restores reading controls and does not accept delayed callbacks',()=>{const {root,box,timers}=setup(class{start(){}abort(){}});let utterance;root.SpeechSynthesisUtterance=class{};root.speechSynthesis={cancel(){},speak(u){utterance=u;}};root.KartEnglishTraining.mount(box,{...q,practiceType:'read'},()=>{});box.children[0].onclick();assert.equal(box.children[1].disabled,true);const t=[...timers.values()].find(x=>x.ms===8000);assert(t);t.fn();assert.equal(box.children[1].disabled,false);const status=box.children.at(-1);assert.match(status.textContent,/未响应/);utterance.onend();assert.match(status.textContent,/未响应/);});
test('recognizer with no events times out, aborts, permits retry and preserves spelling fallback',()=>{let rec,aborts=0;class Recognition{constructor(){rec=this;}start(){}abort(){aborts++;}}const {root,box,timers}=setup(Recognition);let got;root.KartEnglishTraining.mount(box,{...q,practiceType:'read'},x=>got=x);box.children[1].onclick();assert.equal(box.children[1].disabled,true);[...timers.values()].find(x=>x.ms===12000).fn();assert.equal(box.children[1].disabled,false);assert.equal(aborts,1);rec.onresult({results:[[{transcript:'apple'}]]});assert.equal(got,undefined);box.children.find(x=>x.textContent==='改用拼写作答').onclick();const form=box.children.find(x=>x.children?.[0]?.placeholder==='输入英文单词');form.children[0].value='apple';form.onsubmit({preventDefault(){}});assert.equal(got,'apple');});
test('recognizer construction or start errors restore controls without grading wrong',()=>{for(const cls of [class{constructor(){throw Error('no service');}},class{start(){throw Error('no service');}abort(){}}]){const {root,box}=setup(cls);let got;root.KartEnglishTraining.mount(box,{...q,practiceType:'read'},x=>got=x);assert.doesNotThrow(()=>box.children[1].onclick());assert.equal(box.children[1].disabled,false);assert.equal(got,undefined);assert.match(box.children.at(-1).textContent,/无法启动/);}});
test('switching from recognition to sample playback aborts the mic and ignores stale results',()=>{let rec,aborted=false;class Recognition{constructor(){rec=this;}start(){}abort(){aborted=true;}}const {root,box}=setup(Recognition);root.SpeechSynthesisUtterance=class{};root.speechSynthesis={cancel(){},speak(){}};let got;root.KartEnglishTraining.mount(box,{...q,practiceType:'read'},x=>got=x);box.children[1].onclick();box.children[0].onclick();assert.equal(aborted,true);assert.equal(box.children[1].disabled,true);rec.onresult({results:[[{transcript:'apple'}]]});assert.equal(got,undefined);root.KartEnglishTraining.stop();assert.equal(box.children[1].disabled,false);});
