import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const html=fs.readFileSync(new URL('../block-kart/index.html',import.meta.url),'utf8');
const subjectScope={window:{}};vm.createContext(subjectScope);vm.runInContext(fs.readFileSync(new URL('../block-kart/subjects.js',import.meta.url),'utf8'),subjectScope);const KartSubjects=subjectScope.window.KartSubjects;
const bank=JSON.parse(fs.readFileSync(new URL('../block-kart/question-bank.json',import.meta.url)));
test('all grades and subject filters have four-choice questions with one correct answer',()=>{for(let g=1;g<=6;g++)for(const sub of KartSubjects.available(g).filter(s=>s!=='all'))assert(bank.questions.some(q=>q.grade===g&&q.subject===sub));for(const q of bank.questions){assert.equal(q.options.length,4);assert.equal(new Set(q.options).size,4);assert.equal(q.options.filter(x=>x===q.answer).length,1);}});
test('question selection respects grade and subject and avoids immediate repeats',async()=>{const scope={KartSubjects,AbortSignal,fetch:async()=>({ok:true,json:async()=>bank})};vm.createContext(scope);vm.runInContext(fs.readFileSync(new URL('../block-kart/learning.js',import.meta.url),'utf8'),scope);await scope.KartLearning.load();const a=scope.KartLearning.question(4,'math',()=>0),b=scope.KartLearning.question(4,'math',()=>0);assert.equal(a.grade,4);assert.equal(a.subject,'math');assert.notEqual(a.id,b.id);assert.throws(()=>scope.KartLearning.question(9,'math'));});
function setup(){const nodes={};const node=()=>({hidden:true,textContent:'',children:[],appendChild(b){this.children.push(b);this.firstElementChild=this.children[0];},focus(){}});const scope={G:{grade:2,subject:'math',paused:false,studyStats:{total:0,correct:0}},KartLearning:{question:()=>({text:'2+2?',answer:'4',options:['4','3','5','6'],subjectName:'数学',explanation:'正确答案：4'})},document:{createElement:node},$:id=>nodes[id]??=node(),keys:{KeyW:true},T:{steer:1,brake:true,joyBrake:true,drift:true},pickItem(){return 'turbo';},rankOf(){return 0;},engineSound(){},giveItem(k){k.rollT=1.1;},toast(){},emit(){},sfx(){},Math};vm.createContext(scope);vm.runInContext('let itemEdge=false;'+html.slice(html.indexOf('let quizPending = null;'),html.indexOf('function giveItem(k)')),scope);return {scope,nodes};}
test('correct answer pauses and resumes race and awards three items once',()=>{const {scope,nodes}=setup();scope.k={speed:30};vm.runInContext('studyCheckpoint(k)',scope);assert.equal(scope.G.paused,true);nodes['#quizChoices'].children[0].onclick();assert.equal(scope.G.paused,false);assert.equal(scope.k.item,'turbo');assert.equal(scope.k.itemQueue.length,2);assert.equal(scope.G.studyStats.correct,1);nodes['#quizChoices'].children[0].onclick();assert.equal(scope.G.studyStats.total,1);});
test('wrong answer awards no item and leaves driving unchanged',()=>{const {scope,nodes}=setup();scope.k={speed:30,boostT:1};vm.runInContext('studyCheckpoint(k)',scope);nodes['#quizChoices'].children[1].onclick();assert.equal(scope.k.speed,30);assert.equal(scope.k.studySpin,undefined);assert.equal(scope.k.spinT,undefined);assert.equal(scope.k.boostT,1);assert.equal(scope.k.item,undefined);assert.equal(scope.k.itemQueue,undefined);assert.equal(scope.G.studyStats.correct,0);assert.equal(scope.G.paused,false);assert.equal(scope.keys.KeyW,false);});

test('grade curriculum excludes English and IT before grade 3, including mixed questions',async()=>{assert(!KartSubjects.available(1).includes('english'));assert(!KartSubjects.available(2).includes('it'));assert(KartSubjects.available(3).includes('english'));const scope={KartSubjects,AbortSignal,fetch:async()=>({ok:true,json:async()=>bank})};vm.createContext(scope);vm.runInContext(fs.readFileSync(new URL('../block-kart/learning.js',import.meta.url),'utf8'),scope);await scope.KartLearning.load();for(let i=0;i<60;i++){const q=scope.KartLearning.question(1,'all');assert(!['english','it','local'].includes(q.subject));}assert.throws(()=>scope.KartLearning.question(2,'english'));});

test('each selectable subject has varied questions and a full round never repeats',async()=>{const scope={KartSubjects,AbortSignal,fetch:async()=>({ok:true,json:async()=>bank})};vm.createContext(scope);vm.runInContext(fs.readFileSync(new URL('../block-kart/learning.js',import.meta.url),'utf8'),scope);await scope.KartLearning.load();for(let g=1;g<=6;g++)for(const subject of KartSubjects.available(g)){const n=bank.questions.filter(q=>q.grade===g&&(subject==='all'||q.subject===subject)).length;assert(n>=6);const ids=[];for(let i=0;i<n;i++)ids.push(scope.KartLearning.question(g,subject).id);assert.equal(new Set(ids).size,n);assert.notEqual(scope.KartLearning.question(g,subject).id,ids.at(-1));}});

test('finish-line quiz triggers once per completed lap and waits for final answer',()=>{
 const {scope,nodes}=setup();Object.assign(scope.G,{study:true,tr:{N:100},raceTime:42});scope.LAPS=3;scope.computeOrder=()=>{};scope.finishPlayer=()=>{scope.finished=true;};
 scope.k={isPlayer:true,along:-1,item:'turbo'};vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,false);
 scope.k.along=100;vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,true);nodes['#quizChoices'].children[1].onclick();assert.equal(scope.k.studySpin,undefined);assert.equal(scope.G.paused,false);
 vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,false);scope.k.along=99;vm.runInContext('studyLapGate(k)',scope);scope.k.along=101;vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,false);
 scope.k.item=null;scope.k.itemQueue=[];scope.k.along=300;vm.runInContext('studyLapGate(k)',scope);assert(!scope.k.finished);nodes['#quizChoices'].children.at(-4).onclick();assert.equal(scope.k.finished,true);assert.equal(scope.k.finishT,42);assert.equal(scope.finished,true);
});
test('using equipment consumes one queued item at a time',()=>{const {scope}=setup();scope.k={item:'turbo',itemQueue:['turbo','jelly'],heading:0,boostT:0,isPlayer:true};vm.runInContext(html.slice(html.indexOf('function useItem(k,index=0)'),html.indexOf('function hitKart(k)')),scope);vm.runInContext('useItem(k)',scope);assert.equal(scope.k.item,'turbo');assert.equal(scope.k.itemQueue.length,1);vm.runInContext('useItem(k)',scope);assert.equal(scope.k.item,'jelly');assert.equal(scope.k.itemQueue.length,0);});

test('equipment can be used out of order',()=>{const {scope}=setup();scope.k={item:'jelly',itemQueue:['turbo','missile'],heading:0,boostT:0,isPlayer:true};vm.runInContext(html.slice(html.indexOf('function useItem(k,index=0)'),html.indexOf('function hitKart(k)')),scope);vm.runInContext('useItem(k,1)',scope);assert.equal(scope.k.item,'jelly');assert.deepEqual(Array.from(scope.k.itemQueue),['missile']);assert.equal(scope.k.boostT,1.6);});

test('first crossing of start line grants an opening quiz only once',()=>{const {scope,nodes}=setup();Object.assign(scope.G,{study:true,tr:{N:100}});scope.LAPS=3;scope.k={isPlayer:true,along:-5};vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,false);scope.k.along=0;vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,true);nodes['#quizChoices'].children[0].onclick();assert.equal(scope.k.itemQueue.length,2);scope.k.along=-1;vm.runInContext('studyLapGate(k)',scope);scope.k.along=1;vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,false);assert.equal(scope.G.studyStats.total,1);});
