import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const html=fs.readFileSync(new URL('../block-kart/index.html',import.meta.url),'utf8');
const subjectScope={window:{}};vm.createContext(subjectScope);vm.runInContext(fs.readFileSync(new URL('../block-kart/subjects.js',import.meta.url),'utf8'),subjectScope);const KartSubjects=subjectScope.window.KartSubjects;
const bank=JSON.parse(fs.readFileSync(new URL('../block-kart/question-bank.json',import.meta.url)));
test('all grades and subject filters have four-choice questions with one correct answer',()=>{for(let g=1;g<=6;g++)for(const sub of KartSubjects.available(g).filter(s=>s!=='all'))assert(bank.questions.some(q=>q.grade===g&&q.subject===sub));for(const q of bank.questions){assert.equal(q.options.length,4);assert.equal(new Set(q.options).size,4);assert.equal(q.options.filter(x=>x===q.answer).length,1);}});
test('question selection respects grade and subject and avoids immediate repeats',async()=>{const scope={KartSubjects,AbortSignal,fetch:async()=>({ok:true,json:async()=>bank})};vm.createContext(scope);vm.runInContext(fs.readFileSync(new URL('../block-kart/learning.js',import.meta.url),'utf8'),scope);await scope.KartLearning.load();const a=scope.KartLearning.question(4,'math',()=>0),b=scope.KartLearning.question(4,'math',()=>0);assert.equal(a.grade,4);assert.equal(a.subject,'math');assert.notEqual(a.id,b.id);assert.throws(()=>scope.KartLearning.question(9,'math'));});
function setup(){const nodes={};const node=()=>({hidden:true,textContent:'',classList:{toggle(){}},children:[],appendChild(b){this.children.push(b);this.firstElementChild=this.children[0];},focus(){}});const scope={LAPS:6,performance:{now:()=>1000},MUSIC:{stop(){}},G:{grade:2,subject:'math',paused:false,studyStats:{total:0,correct:0}},KartLearning:{question:()=>({text:'2+2?',answer:'4',options:['4','3','5','6'],subjectName:'数学',explanation:'正确答案：4'})},KartEnglishTraining:{stop(){},mount(box,q,submit){q.options.forEach(a=>{const b=node();b.onclick=()=>submit(a);box.appendChild(b);});}},document:{createElement:node},$:id=>nodes[id]??=node(),keys:{KeyW:true},T:{steer:1,brake:true,joyBrake:true,drift:true},pickItem(){return 'shield';},rankOf(){return 0;},engineSound(){},giveItem(k){k.rollT=1.1;},toast(){},emit(){},sfx(){},Math};vm.createContext(scope);vm.runInContext('let itemEdge=false;'+html.slice(html.indexOf('let quizPending = null;'),html.indexOf('function giveItem(k)')),scope);return {scope,nodes};}
test('correct answer immediately resumes without feedback and awards three items once',()=>{const {scope,nodes}=setup();scope.k={speed:30};vm.runInContext('studyCheckpoint(k)',scope);assert.equal(scope.G.paused,true);nodes['#quizChoices'].children[0].onclick();assert.equal(nodes['#quizOv'].hidden,true);assert.equal(nodes['#quizReview'].hidden,true);assert.equal(nodes['#quizContinue'].onclick,null);assert.equal(scope.G.paused,false);assert.equal(scope.k.item,'shield');assert.equal(scope.k.itemQueue.length,2);assert.equal(scope.G.studyStats.correct,1);nodes['#quizChoices'].children[0].onclick();assert.equal(scope.G.studyStats.total,1);});
test('wrong answer awards no item and leaves driving unchanged',()=>{const {scope,nodes}=setup();scope.k={speed:30,boostT:1};vm.runInContext('studyCheckpoint(k)',scope);nodes['#quizChoices'].children[1].onclick();nodes['#quizContinue'].onclick();assert.equal(scope.k.speed,30);assert.equal(scope.k.studySpin,undefined);assert.equal(scope.k.spinT,undefined);assert.equal(scope.k.boostT,1);assert.equal(scope.k.item,undefined);assert.equal(scope.k.itemQueue,undefined);assert.equal(scope.G.studyStats.correct,0);assert.equal(scope.G.paused,false);assert.equal(scope.keys.KeyW,false);});

test('early grades have English foundations and mixed selection is English only',async()=>{assert(KartSubjects.available(1).includes('english'));assert(!KartSubjects.available(2).includes('it'));const scope={KartSubjects,AbortSignal,fetch:async()=>({ok:true,json:async()=>bank})};vm.createContext(scope);vm.runInContext(fs.readFileSync(new URL('../block-kart/learning.js',import.meta.url),'utf8'),scope);await scope.KartLearning.load();for(let i=0;i<30;i++)assert.equal(scope.KartLearning.question(1,'all').subject,'english');assert.equal(scope.KartLearning.question(2,'english').grade,2);});

test('each selectable subject has varied questions and a full round never repeats',async()=>{const scope={KartSubjects,AbortSignal,fetch:async()=>({ok:true,json:async()=>bank})};vm.createContext(scope);vm.runInContext(fs.readFileSync(new URL('../block-kart/learning.js',import.meta.url),'utf8'),scope);await scope.KartLearning.load();for(let g=1;g<=6;g++)for(const subject of KartSubjects.available(g)){const n=bank.questions.filter(q=>q.difficulty==='thinking'&&q.grade===g&&(subject==='all'?q.subject==='english':q.subject===subject)).length;assert(n>=100);const ids=[];for(let i=0;i<n;i++)ids.push(scope.KartLearning.question(g,subject).id);assert.equal(new Set(ids).size,n);assert.notEqual(scope.KartLearning.question(g,subject).id,ids.at(-1));}});

test('finish-line quiz triggers once per completed lap and waits for final answer',()=>{
 const {scope,nodes}=setup();Object.assign(scope.G,{study:true,tr:{N:100},raceTime:42});scope.LAPS=3;scope.computeOrder=()=>{};scope.finishPlayer=()=>{scope.finished=true;};
 scope.k={isPlayer:true,along:-1,item:'shield'};vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,false);
 scope.k.along=100;vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,true);nodes['#quizChoices'].children[1].onclick();nodes['#quizContinue'].onclick();assert.equal(scope.k.studySpin,undefined);assert.equal(scope.G.paused,false);
 vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,false);scope.k.along=99;vm.runInContext('studyLapGate(k)',scope);scope.k.along=101;vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,false);
 scope.k.item=null;scope.k.itemQueue=[];scope.k.along=300;vm.runInContext('studyLapGate(k)',scope);assert(!scope.k.finished);nodes['#quizChoices'].children.at(-4).onclick();assert.equal(scope.k.finished,true);assert.equal(scope.k.finishT,42);assert.equal(scope.finished,true);
});
test('using I leaves O and P fixed, and O still works with I empty',()=>{const {scope}=setup();scope.k={item:'shield',itemQueue:['shield','missile'],heading:0,boostT:0,isPlayer:true};vm.runInContext(html.slice(html.indexOf('function useItem(k,index=0)'),html.indexOf('function hitKart(k,owner,ice=false)')),scope);vm.runInContext('useItem(k,0)',scope);assert.equal(scope.k.item,null);assert.deepEqual(Array.from(scope.k.itemQueue),['shield','missile']);vm.runInContext('useItem(k,1)',scope);assert.deepEqual(Array.from(scope.k.itemQueue),[null,'missile']);vm.runInContext('awardStudyItems(k,3)',scope);assert.equal(scope.k.item,'shield');assert.deepEqual(Array.from(scope.k.itemQueue),['shield','missile']);});
test('using O leaves I and P in their original positions',()=>{const {scope}=setup();scope.k={item:'jelly',itemQueue:['shield','missile'],heading:0,boostT:0,isPlayer:true};vm.runInContext(html.slice(html.indexOf('function useItem(k,index=0)'),html.indexOf('function hitKart(k,owner,ice=false)')),scope);vm.runInContext('useItem(k,1)',scope);assert.equal(scope.k.item,'jelly');assert.deepEqual(Array.from(scope.k.itemQueue),[null,'missile']);assert.equal(scope.k.shieldT,8);});

test('first crossing of start line grants an opening quiz only once',()=>{const {scope,nodes}=setup();Object.assign(scope.G,{study:true,tr:{N:100}});scope.LAPS=3;scope.k={isPlayer:true,along:-5};vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,false);scope.k.along=0;vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,true);nodes['#quizChoices'].children[0].onclick();assert.equal(scope.k.itemQueue.length,2);scope.k.along=-1;vm.runInContext('studyLapGate(k)',scope);scope.k.along=1;vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,false);assert.equal(scope.G.studyStats.total,1);});

test('correct rewards fill only vacant slots without replacing existing equipment',()=>{for(const initial of [[],['missile'],['missile','jelly'],['missile','jelly','missile']]){const {scope}=setup();scope.k={item:initial[0]||null,itemQueue:initial.slice(1),isPlayer:true};vm.runInContext('awardStudyItems(k,3)',scope);const held=[scope.k.item,...scope.k.itemQueue];assert.equal(held.length,3);assert.deepEqual(held.slice(0,initial.length),initial);}});

test('mobile item action consumes the leftmost occupied slot and skips vacancies',()=>{const {scope}=setup();scope.k={item:'shield',itemQueue:['shield','shield'],heading:0,boostT:0,isPlayer:true};vm.runInContext(html.slice(html.indexOf('function useItem(k,index=0)'),html.indexOf('function hitKart(k,owner,ice=false)')),scope);for(let i=0;i<3;i++){vm.runInContext('useItem(k,-1)',scope);assert.deepEqual([scope.k.item,...scope.k.itemQueue],Array.from({length:3},(_,j)=>j<=i?null:'shield'));}vm.runInContext('useItem(k,-1)',scope);assert.deepEqual([scope.k.item,...scope.k.itemQueue],[null,null,null]);scope.k.itemQueue=[null,'shield'];vm.runInContext('useItem(k,-1)',scope);assert.deepEqual([scope.k.item,...scope.k.itemQueue],[null,null,null]);});

test('olympiad has grade-specific banks and remains an opt-in extension',async()=>{const scope={KartSubjects,AbortSignal,fetch:async()=>({ok:true,json:async()=>bank})};vm.createContext(scope);vm.runInContext(fs.readFileSync(new URL('../block-kart/learning.js',import.meta.url),'utf8'),scope);await scope.KartLearning.load();for(let grade=1;grade<=6;grade++){const questions=bank.questions.filter(q=>q.grade===grade&&q.subject==='olympiad');assert(questions.length>=100);assert(new Set(questions.map(q=>q.topic)).size>=15);assert.equal(scope.KartLearning.question(grade,'olympiad').subject,'olympiad');for(let i=0;i<50;i++)assert.notEqual(scope.KartLearning.question(grade,'all').subject,'olympiad');}});

test('every offered grade and subject has reasoning questions with explanations',()=>{for(let g=1;g<=6;g++)for(const sub of KartSubjects.available(g).filter(s=>s!=='all')){const pool=bank.questions.filter(q=>q.grade===g&&q.subject===sub&&q.difficulty==='thinking');assert(pool.length>=100);assert(pool.every(q=>typeof q.explanation==='string'&&q.explanation.trim().length>0));}});
test('answer review pauses race, prevents duplicate scoring and resumes on explicit continue',()=>{const {scope,nodes}=setup();scope.k={speed:30};vm.runInContext('studyCheckpoint(k)',scope);nodes['#quizChoices'].children[1].onclick();assert.equal(scope.G.paused,true);assert.equal(scope.k.item,undefined);assert.equal(nodes['#quizReview'].hidden,false);assert(nodes['#quizExplanation'].textContent.includes('解题思路'));nodes['#quizChoices'].children[0].onclick();assert.equal(scope.G.studyStats.total,1);nodes['#quizContinue'].onclick();assert.equal(scope.G.paused,false);assert.equal(scope.k.itemQueue,undefined);assert.equal(scope.G.studyStats.correct,0);});
test('final correct answer finishes without granting unusable equipment',()=>{const {scope,nodes}=setup();Object.assign(scope.G,{study:true,tr:{N:100},raceTime:42});scope.LAPS=6;scope.computeOrder=()=>{};scope.finishPlayer=()=>{};scope.k={isPlayer:true,along:600,item:null,itemQueue:[]};vm.runInContext('studyLapGate(k)',scope);nodes['#quizChoices'].children[0].onclick();assert.equal(scope.k.finished,true);assert.equal(scope.k.item,null);assert.equal(scope.k.itemQueue.length,0);assert.equal(scope.G.studyStats.correct,1);});

test('midpoint gives one quiz per lap, fills vacancies, and reversing cannot retrigger',()=>{const {scope,nodes}=setup();Object.assign(scope.G,{study:true,tr:{N:100}});scope.k={isPlayer:true,along:0};vm.runInContext('studyLapGate(k)',scope);nodes['#quizChoices'].children.at(-4).onclick();scope.k.item=null;scope.k.along=49;vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,false);scope.k.along=50;vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,true);assert.equal(nodes['#quizTitle'].textContent,'半圈答题');nodes['#quizChoices'].children.at(-4).onclick();assert.equal(scope.k.item,'shield');assert.equal(scope.G.studyStats.total,2);for(const x of [49,50,51]){scope.k.along=x;vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,false);}scope.k.along=100;vm.runInContext('studyLapGate(k)',scope);assert.equal(nodes['#quizTitle'].textContent,'终点答题');});
test('six complete laps issue thirteen checkpoints and finish only after the final answer',()=>{const {scope,nodes}=setup();Object.assign(scope.G,{study:true,tr:{N:100},raceTime:180});scope.computeOrder=()=>{};scope.finishPlayer=()=>{};scope.k={isPlayer:true,along:-1};for(let gate=0;gate<=12;gate++){scope.k.along=gate*50;vm.runInContext('studyLapGate(k)',scope);assert.equal(scope.G.paused,true);assert(!scope.k.finished);nodes['#quizChoices'].children.at(-4).onclick();assert.equal(scope.G.paused,false);}assert.equal(scope.G.studyStats.total,13);assert.equal(scope.k.finished,true);});
