import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {webcrypto} from 'node:crypto';
import {VERSION,TRACK_VERSION,BANK_VERSION,playlist,answerHash,validateFinish,validQuestion} from '../game/backend/rules.mjs';
const root=new URL('../block-kart/',import.meta.url),html=fs.readFileSync(new URL('index.html',root),'utf8');
function setup(api={call:async()=>({ok:true})}){const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};const ctx={localStorage:storage,crypto:webcrypto,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),GameAPI:api,AbortSignal,fetch:async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(new URL('question-bank.json',root)))})};ctx.window=ctx;vm.createContext(ctx);for(const f of ['subjects.js','season.js','progression.js','reliable-save.js','learning.js'])vm.runInContext(fs.readFileSync(new URL(f,root),'utf8'),ctx);return {ctx,storage,data};}
test('failed upload survives reload, retries only owner, and successful idempotent retry clears exactly that run',async()=>{let online=false,calls=0;const {ctx,storage}=setup({call:async()=>{calls++;if(!online)throw Error('offline');return {ok:true,alreadySaved:true};}});let q=ctx.KartSaveFactory(storage,ctx.GameAPI);q.enqueue('alice',{runId:'a'});q.enqueue('bob',{runId:'b'});assert.equal((await q.flush('alice')).pending,1);q=ctx.KartSaveFactory(storage,ctx.GameAPI);online=true;assert.equal((await q.flush('alice')).saved,1);assert.deepEqual(Array.from(q.read(),x=>x.username),['bob']);assert.equal(calls,2);});
test('validation errors retain a local blocked record and quota errors do not claim persistence',async()=>{const {ctx,storage}=setup({call:async()=>{throw Object.assign(Error('invalid'),{status:400});}});const q=ctx.KartSaveFactory(storage,ctx.GameAPI);q.enqueue('a',{runId:'r'});await q.flush('a');assert.equal(q.read()[0].blocked,true);storage.setItem=()=>{throw Error('quota');};assert.throws(()=>q.enqueue('a',{runId:'next'}),/quota/);});
test('server playlist equals client seeded playlist for all supported grade/subject pools',async()=>{const {ctx}=setup();await ctx.KartLearning.load();for(let grade=1;grade<=6;grade++)for(const subject of ctx.KartSubjects.available(grade)){const c={grade,subject};assert.deepEqual(Array.from(ctx.KartLearning.playlist(grade,subject,13,12345)),playlist(c,13,12345));}});
test('challenge code rejects malformed and old versions; defaults stay six laps',()=>{const {ctx}=setup(),s=ctx.KartSeason,c={v:VERSION,mode:'friend',track:1,diff:1,study:true,grade:4,subject:'english',seed:123};const code=s.encode(c);assert.equal(s.decode(code).seed,123);assert.equal(s.decode('bad'),null);assert.equal(s.decode('BK2-'+Buffer.from(JSON.stringify({...c,v:'old'})).toString('base64')),null);assert.equal(s.laps('race'),6);assert.equal(s.laps('quick'),1);assert.equal(s.laps('practice'),1);assert.equal(s.questions(6),13);assert.equal(s.questions(1),3);assert.notEqual(s.key(c),s.key({...c,mode:'race'}));});
test('server validates issued answer order, supported curriculum, laps, timing, versions and expiry',()=>{const c={grade:4,subject:'english'},ids=playlist(c,13,123),r={started:0},m={rules:VERSION,track_version:TRACK_VERSION,bank:BANK_VERSION,laps:6,questions:JSON.stringify(ids),expires:700000};const b={rules:VERSION,ms:180000,laps:6,hits:3,lapTimes:Array(6).fill(30000),answers:ids.map(id=>({id,answer:'test'}))};assert.deepEqual(validateFinish(b,r,m,200000),ids);for(const bad of [{...b,ms:1000},{...b,lapTimes:[180000]},{...b,laps:1},{...b,answers:b.answers.slice(1)},{...b,rules:'old'},{...b,hits:121}])assert.throws(()=>validateFinish(bad,r,m,200000));assert.throws(()=>validateFinish(b,r,m,800000));assert.equal(validQuestion(ids[0],{grade:1,subject:'english'}),false);assert(answerHash(ids[0]));});
test('experience is independent from inventory; wrong answers have no XP, review does not farm XP, and due dates persist',()=>{const {ctx,storage}=setup();let p=ctx.KartProgressFactory(storage);const q={id:'q',grade:4,subject:'math',topic:'分数',options:['1','2','3','4'],answer:'1',text:'test'};p.answer(q,false);assert.equal(p.read().xp,0);assert.equal(p.due(4,'math').length,0);for(let i=0;i<3;i++)p.finish();assert.equal(p.due(4,'math').length,1);p=ctx.KartProgressFactory(storage);p.answer(q,true,{review:true});assert.equal(p.read().xp,60);assert.equal(p.read().wrong[0].resolved,true);p.answer(q,true);assert.equal(p.read().xp,70);assert.equal(p.read().topics['4:math:分数'].total,3);assert.equal(p.cosmetics.filter(c=>c.xp<=p.read().xp).length,1);});
test('grade shards exactly preserve canonical content and server answer hashes',async()=>{const bank=JSON.parse(fs.readFileSync(new URL('question-bank.json',root))),all=[];for(let grade=1;grade<=6;grade++){const shard=JSON.parse(fs.readFileSync(new URL('questions/grade-'+grade+'.json',root)));assert(shard.questions.every(q=>q.grade===grade));all.push(...shard.questions);}assert.equal(all.length,bank.questions.length);const source=new Map(bank.questions.map(q=>[q.id,q]));for(const q of all){assert.deepEqual(q,source.get(q.id));assert.equal(answerHash(q.id),Buffer.from(await webcrypto.subtle.digest('SHA-256',new TextEncoder().encode(q.answer))).toString('hex'));}});
test('assisted drift holds to charge then releases without extra touch buttons',()=>{const scope={G:{touch:true,control:'buttons',state:'race',paused:false,assistDrift:true,assistElapsed:0,assistSign:0},keys:{},T:{left:true,right:false,throttle:true,brake:false},navigator:{},KartTilt:{steer:()=>0},clamp:(v,a,b)=>Math.max(a,Math.min(b,v))};vm.createContext(scope);vm.runInContext('let itemEdge=false,itemChoice=0,padItemPrev=false;'+html.slice(html.indexOf('function readInput('),html.indexOf('/* ================= race logic')),scope);for(let i=0;i<10;i++)vm.runInContext('readInput(.05)',scope);assert.equal(vm.runInContext('readInput(.05).drift',scope),true);scope.T.left=false;assert.equal(vm.runInContext('readInput(.05).drift',scope),false);assert.equal(scope.G.assistElapsed,0);});

test('new module globals remain available when globalThis is a distinct host object',()=>{const ctx={globalThis:{}};vm.createContext(ctx);for(const f of ['season.js','progression.js','reliable-save.js'])vm.runInContext(fs.readFileSync(new URL(f,root),'utf8'),ctx);assert.equal(typeof ctx.KartSaveFactory,'function');assert.equal(typeof ctx.KartProgressFactory,'function');assert.equal(ctx.KartSeason.laps('race'),6);});
test('a startup exception restores controls instead of leaving loading locked',async()=>{const nodes=new Map(),get=id=>{if(!nodes.has(id))nodes.set(id,{inert:false,disabled:false,textContent:''});return nodes.get(id);};const ctx={setAutopilot(){},requestLandscape:async()=>{},syncOrientation:()=>false,G:{study:true},KartPlayLimit:{tick:()=>({locked:false})},$:get,enableTouchControl:async()=>{throw Error('startup fixture');},toast:()=>{},console:{error:()=>{}}};vm.createContext(ctx);vm.runInContext(html.slice(html.indexOf('async function startRace()'),html.indexOf('function toMenu()')),ctx);await ctx.startRace();assert.equal(ctx.G.starting,false);assert.equal(get('#startBtn').disabled,false);assert.equal(get('#startBtn').textContent,'开始比赛 →');assert.equal(get('#menu').inert,false);});

test('previous English issued runs remain savable in their original season',()=>{const ids=playlist({grade:4,subject:'english'},7,123),old='kart-english-20261003',m={rules:old,track_version:TRACK_VERSION,bank:BANK_VERSION,laps:6,questions:JSON.stringify(ids),expires:700000},b={rules:old,ms:180000,laps:6,hits:0,lapTimes:Array(6).fill(30000),answers:ids.map(id=>({id,answer:'test'}))};assert.deepEqual(validateFinish(b,{started:0},m,200000),ids);assert.throws(()=>validateFinish({...b,rules:VERSION},{started:0},m,200000));});
