var KartExperience;
(function(root){
'use strict';
let memory={};const storage={getItem(k){try{return localStorage.getItem(k);}catch{return memory[k];}},setItem(k,v){localStorage.setItem(k,v);memory[k]=v;}};
const progress=KartProgressFactory(storage),queue=KartSaveFactory(storage,GameAPI);
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let modalStack=[];let mounted=false,reviewQ=null,activeReport=null,trainingStep=0,trainingComplete=false,reportBusy=false;
function modal(id,title){const ov=el('div',undefined,'overlay exp-overlay');ov.id=id;ov.hidden=true;ov.setAttribute('role','dialog');ov.setAttribute('aria-modal','true');const d=el('div',undefined,'dialog panel exp-dialog'),h=el('h2',title);h.id=id+'Title';h.tabIndex=-1;h.style.outline='none';ov.setAttribute('aria-labelledby',h.id);d.append(h);ov.append(d);document.body.append(ov);return d;}
function open(id){modalStack=modalStack.filter(x=>x!==id);modalStack.push(id);for(const n of document.body.children)if(n.tagName!=='SCRIPT')n.inert=n!==$(id);$(id).hidden=false;$(id).style.zIndex=120+modalStack.length;$(id+'Title').focus({preventScroll:true});}
function button(text,fn,cls='alt'){const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;}
function close(id){$(id).hidden=true;modalStack=modalStack.filter(x=>x!==id);const top=modalStack.at(-1);for(const n of document.body.children)if(n.tagName!=='SCRIPT')n.inert=top?n!==$(top):false;if(top){$(top+'Title').focus({preventScroll:true});return;}if(!$('quizOv').hidden){$('quizTitle').focus({preventScroll:true});return;}const g=root.__bk?.G;if(g?.state==='menu')$('startBtn').focus();else if(g?.state==='results')$('againBtn').focus();}
function notify(text){const t=$('toast');t.textContent=text;t.hidden=false;setTimeout(()=>t.hidden=true,2500);}
function info(){const s=progress.read();$('progressSummary').textContent=`${progress.title(s)} · 学习经验 ${s.xp} · 完成 ${s.runs} 场`;
 const select=$('paintSelect'),saved=localStorage.getItem('bk_paint')||'classic';select.textContent='';for(const c of progress.cosmetics){const o=el('option',c.name+(s.xp<c.xp?`（${c.xp}经验解锁）`:''));o.value=c.id;o.disabled=s.xp<c.xp;select.append(o);}select.value=progress.cosmetics.some(c=>c.id===saved&&s.xp>=c.xp)?saved:'classic';}
function currentConfig(mode=root.__bk.G.mode){const g=root.__bk.G;return {v:KartSeason.RULES,mode,track:g.trackIdx,diff:g.diff,study:g.study,grade:g.grade,subject:g.subject,seed:g.seed||0};}
function applyChallenge(c){const g=root.__bk.G;Object.assign(g,{mode:c.mode==='weekly'?'weekly':'friend',trackIdx:c.track,diff:c.diff,study:c.study,grade:c.grade,subject:c.subject,seed:c.seed});g.challenge=c;root.__bk.refreshMenu();$('modeSelect').value=g.mode;$('challengeInfo').textContent=`${c.mode==='weekly'?'本周挑战':'朋友挑战'} · 相同题目、赛道与随机种子`;$('studyMode').disabled=$('studySubject').disabled=true;$('studyGrade').disabled=g.mode==='friend';}
function changeMode(){const g=root.__bk.G;g.mode=$('modeSelect').value;g.challenge=null;if(g.mode==='weekly'){applyChallenge(KartSeason.weekly(g.grade));return;}$('studyMode').disabled=$('studyGrade').disabled=$('studySubject').disabled=false;$('challengeInfo').textContent=g.mode==='practice'?'一圈练习，成绩只记本机，不进入云端排行榜。':g.mode==='quick'?'一圈快速挑战，与六圈比赛分别记录。':'六圈完整比赛，默认模式。';root.__bk.refreshMenu();}
async function flush(){if(root.__bk?.G.unsavedBody&&root.__bk.G.cloudUser){try{queue.enqueue(root.__bk.G.cloudUser.username,root.__bk.G.unsavedBody);root.__bk.G.unsavedBody=null;}catch{try{await GameAPI.call('/finish',root.__bk.G.unsavedBody);root.__bk.G.unsavedBody=null;$('saveStatus').textContent='云端成绩已保存';}catch{$('saveStatus').textContent='暂时无法上传，请稍后重试。';}return;}}const username=root.__bk?.G.cloudUser?.username;if(!username)return;try{const r=await queue.flush(username);$('saveStatus').textContent=r.error?`成绩已保存在本机，待上传 ${r.pending} 场。${r.error}`:r.pending?`本机待上传 ${r.pending} 场`:'云端成绩已保存';}catch{$('saveStatus').textContent='本机存储空间不足，请保持页面打开后重试。';}}
async function reportFlush(){if(reportBusy)return;reportBusy=true;try{for(const r of progress.read().reports){try{await GameAPI.call('/question-report',r);progress.removeReport(r.id);}catch{break;}}}finally{reportBusy=false;}}
function showProgress(){const g=root.__bk.G,s=progress.read(),body=$('progressBody');body.textContent='';body.append(el('p',`${progress.title(s)} · ${s.xp}经验。每次比赛答对 +10，完成比赛 +20。复习不重复刷经验。`,'exp-note'));const topics=Object.values(s.topics).filter(t=>t.grade===g.grade&&(g.subject==='all'||t.subject===g.subject));
 body.append(el('p',`${g.grade}年级 · ${KartSubjects.names[g.subject]} · 掌握情况仅代表本机练习记录。`,'exp-note'));if(!topics.length)body.append(el('p','完成答题后，这里会显示知识点进度。'));
 for(const t of topics){const card=el('div',undefined,'exp-card'),rate=Math.round(t.correct/t.total*100),bar=el('div',undefined,'exp-progress'),fill=el('span');fill.style.width=rate+'%';bar.append(fill);card.append(el('h3',`${KartSubjects.names[t.subject]} · ${t.name}`),el('p',`${t.correct}/${t.total}次正确 · 正确率${rate}% · ${t.streak>=3?'连续答对，继续巩固':'练习中'}`),bar);body.append(card);}open('progressOv');}
function showWrong(){const body=$('wrongBody');body.textContent='';const g=root.__bk.G,wrong=progress.read().wrong.filter(x=>x.q.grade===g.grade&&(g.subject==='all'||x.q.subject===g.subject)).slice().reverse();if(!wrong.length)body.append(el('p','当前题库还没有错题。'));
 for(const x of wrong){const card=el('div',undefined,'exp-card');card.append(el('h3',`${x.q.grade}年级 · ${KartSubjects.names[x.q.subject]}${x.resolved?' · 已复习':''}`),el('p',x.q.text));card.append(button('重新作答',()=>reviewQuestion(x.q)));body.append(card);}open('wrongOv');}
function reviewQuestion(q){reviewQ=q;const body=$('reviewBody');body.textContent='';body.append(el('p',q.text));const opts=el('div',undefined,'exp-options'),result=el('p','先独立思考，再选择答案。','exp-status');for(const a of q.options){const b=button(a,()=>{for(const x of opts.children)x.disabled=true;const correct=a===q.answer;progress.answer(q,correct,{review:true});progress.event('review_answer');result.textContent=(correct?'答对了。':'正确答案：'+q.answer+'。')+' 解题思路：'+q.explanation;info();});opts.append(b);}body.append(opts,result,button('题目有问题',()=>reportQuestion(q)));open('reviewOv');}
function reportQuestion(q){activeReport=q;$('reportStatus').textContent='只提交题目编号和问题类型。';open('reportOv');}
function tutorial(){trainingStep=0;trainingComplete=false;renderTutorial();progress.event('training_open');open('tutorialOv');}
function renderTutorial(){const body=$('tutorialBody');body.textContent='';const car=el('div','🏎️');car.id='tutorialCar';body.append(car);
 const label=['第一步：转向','第二步：使用护盾','第三步：选择答案','训练完成'][trainingStep];body.append(el('h3',label));
 if(trainingStep===0){body.append(el('p','按 A / D 或点击方向键，观察赛车转向。'));for(const [name,deg] of [['◀ 向左',-20],['向右 ▶',20]])body.append(button(name,()=>{car.style.transform=`rotate(${deg}deg)`;trainingComplete=true;$('tutorialNext').disabled=false;}));const b=button('下一步',()=>{trainingStep=1;renderTutorial();});b.id='tutorialNext';b.disabled=true;body.append(b);}
 if(trainingStep===1){body.append(el('p','电脑 I/O/P 对应固定三格；手机点击左侧道具按钮，依次使用。现在按 I 或点击护盾。'));body.append(button('I · 气泡护盾',()=>{if(trainingStep!==1)return;car.classList.add('shield');body.append(el('p','护盾已开启，能抵挡一次攻击。'));trainingStep=2;setTimeout(renderTutorial,900);}));}
 if(trainingStep===2){body.append(el('p','小明有3盒铅笔，每盒4支，送出5支，还剩多少支？'));for(const a of ['7支','12支','17支'])body.append(button(a,()=>{if(a!=='7支'){notify('先算3×4，再减5。再试一次。');return;}trainingStep=3;renderTutorial();progress.event('training_complete');}));}
 if(trainingStep===3){body.append(el('p','比赛答对直接继续并补空格；答错看解析后继续。持续方向键可辅助漂移，松开方向键释放加速。'));body.append(button('进入一圈练习',()=>{close('tutorialOv');$('modeSelect').value='practice';changeMode();root.__bk.startRace();},'big'));}
}
function metrics(){const s=progress.read(),m=s.metrics,body=$('metricsBody');body.textContent='';const pairs=[['开赛次数',m.start||0],['完成次数',m.finish||0],['完成率',m.start?Math.round((m.finish||0)/m.start*100)+'%':'—'],['连续再开一场',(m.second_race||0)],['游玩天数',s.days.length],['答题平均思考时间',m.answer?((m.answer_ms||0)/m.answer/1000).toFixed(1)+'秒':'—'],['保存失败次数',m.save_fail||0],['低帧率采样',m.slow_frame||0]];for(const [k,v] of pairs)body.append(el('p',k+'：'+v));body.append(button('查看全站匿名汇总',async()=>{try{const r=await GameAPI.call('/metrics-summary');const out=el('div',undefined,'exp-card');out.append(el('p','自愿参与统计的玩家计数；不能代表全部玩家。'));for(const x of r.rows)out.append(el('p',`${x.day} · ${x.event}：${x.count}`));body.append(out);}catch{body.append(el('p','统计服务暂时不可用。'));}}));body.append(el('p','本机数据不代表全站。匿名汇总默认关闭，可在学习进度与外观中自愿开启。需积累玩家回访数据后再决定实时多人联机。','exp-note'));open('metricsOv');}
function mount(){if(mounted)return;mounted=true;const g=root.__bk.G;g.mode='race';g.seed=0;g.assistDrift=localStorage.getItem('bk_assistDrift')==='true';
 const settings=el('section'),label=el('label','比赛模式','exp-label'),mode=el('select');mode.id='modeSelect';for(const [v,t] of [['race','完整比赛 · 6圈'],['quick','快速挑战 · 1圈'],['practice','练习模式 · 1圈'],['weekly','本周年级综合挑战 · 6圈'],['friend','朋友挑战']]){const o=el('option',t);o.value=v;mode.append(o);}label.append(mode);const note=el('p','六圈完整比赛，默认模式。','exp-note');note.id='challengeInfo';const row=el('div',undefined,'exp-row');row.append(button('操作训练',tutorial),button('朋友挑战',()=>open('challengeOv')));settings.append(label,note,row);$('menu').children[0].after(settings);mode.onchange=()=>{if(mode.value==='friend'){mode.value=g.mode;open('challengeOv');return;}changeMode();};
 const assist=el('label',undefined,'keys');assist.style.display='block';assist.style.marginTop='12px';const check=el('input');check.type='checkbox';check.checked=g.assistDrift;check.onchange=()=>{g.assistDrift=check.checked;localStorage.setItem('bk_assistDrift',String(check.checked));};assist.append(check,document.createTextNode('辅助漂移：持续转向蓄力，松开释放'));$('controlSettings').append(assist);
 const details=el('details'),sum=el('summary','学习进度与外观');sum.style.color='var(--gold)';const p=el('p',undefined,'exp-note');p.id='progressSummary';const paintLabel=el('label','车漆（仅外观）','exp-label'),paint=el('select');paint.id='paintSelect';paintLabel.append(paint);paint.onchange=()=>{localStorage.setItem('bk_paint',paint.value);root.__bk.refreshMenu();};const metricsLabel=el('label',undefined,'exp-note'),metricsCheck=el('input');metricsCheck.type='checkbox';metricsCheck.checked=localStorage.getItem('bk_metrics_optin')==='true';metricsCheck.onchange=()=>{localStorage.setItem('bk_metrics_optin',String(metricsCheck.checked));if(metricsCheck.checked)KartTelemetry.flush();};metricsLabel.append(metricsCheck,document.createTextNode('允许匿名汇总开赛、完赛、回访和保存失败次数（不含账号、答案或驾驶轨迹）'));details.append(sum,p,paintLabel,metricsLabel,button('知识点进度',showProgress),button('错题回顾',showWrong),button('本机游玩统计',metrics));$('controlSettings').after(details);
 const combat=el('div');combat.id='combatInfo';combat.hidden=true;const tip=el('div');tip.id='raceTip';tip.hidden=true;$('hud').append(combat,tip);
 const summary=el('div');summary.id='resSummary';$('resScore').before(summary);const save=el('p');save.id='saveStatus';$('resBest').after(save);$('resScore').after(button('本场错题与复习',()=>showRaceWrong()),button('重试成绩上传',flush));
 const feedback=button('题目有问题',()=>{const q=root.__bk.currentQuiz();if(q)reportQuestion(q);});feedback.id='feedbackBtn';$('quizOv').firstElementChild.append(feedback);
 const pd=modal('progressOv','知识点进度'),pb=el('div');pb.id='progressBody';pd.append(pb,button('关闭',()=>close('progressOv')));
 const wd=modal('wrongOv','错题回顾'),wb=el('div');wb.id='wrongBody';wd.append(wb,button('关闭',()=>close('wrongOv')));
 const rd=modal('reviewOv','复习作答'),rb=el('div');rb.id='reviewBody';rd.append(rb,button('返回',()=>close('reviewOv')));
 const fd=modal('reportOv','题目反馈'),sel=el('select');sel.id='reportReason';for(const x of ['乱码或显示问题','题目或答案有误','超出年级范围','题意不清'])sel.append(el('option',x));const status=el('p');status.id='reportStatus';fd.append(sel,status,button('提交反馈',async()=>{if(!activeReport)return;try{progress.report(activeReport,sel.value);}catch(e){$('reportStatus').textContent=e.message;return;}activeReport=null;$('reportStatus').textContent='反馈已保存，网络可用时自动提交。';await reportFlush();if(!progress.read().reports.length)$('reportStatus').textContent='反馈已提交，谢谢。';}),button('返回',()=>close('reportOv')));
 const td=modal('tutorialOv','操作训练'),tb=el('div');tb.id='tutorialBody';td.append(tb,button('关闭',()=>close('tutorialOv')));
 const cd=modal('challengeOv','朋友挑战'),cp=el('p','分享后，朋友使用相同赛道、难度、题目和随机种子；当前为异步比成绩。','exp-note'),input=el('input');input.id='challengeCode';input.placeholder='粘贴 BK2- 开头的挑战码';const cs=el('p');cs.id='challengeStatus';cd.append(cp,button('生成并复制挑战链接',async()=>{const c=currentConfig('friend');c.seed=root.crypto.getRandomValues(new Uint32Array(1))[0];const code=KartSeason.encode(c),url=location.origin+location.pathname+'?challenge='+encodeURIComponent(code);input.value=code;try{await navigator.clipboard.writeText(url);cs.textContent='已复制。保存这个挑战码可再次挑战。';}catch{cs.textContent='复制不可用，请手动复制下面的挑战码。';}applyChallenge(c);}),input,cs,button('载入挑战码',()=>{const raw=input.value.trim();let code=raw;try{if(raw.includes('://'))code=new URL(raw).searchParams.get('challenge');}catch{}const c=KartSeason.decode(code);if(!c){cs.textContent='挑战码无效或属于旧版本。';return;}if(c.mode==='weekly')c.mode='friend';applyChallenge(c);cs.textContent='挑战已载入，关闭后开始比赛。';}),button('关闭',()=>close('challengeOv')));
 const md=modal('metricsOv','本机游玩统计'),mb=el('div');mb.id='metricsBody';md.append(mb,button('关闭',()=>close('metricsOv')));
 info();const code=new URLSearchParams(location.search).get('challenge');if(code){const c=KartSeason.decode(code);if(c){c.mode='friend';applyChallenge(c);}else notify('挑战码无效或版本已更新');}
 const handler=()=>{flush();reportFlush();};root.addEventListener('online',handler);root.addEventListener('kart-account',handler);setInterval(handler,30000);
 root.addEventListener('keydown',e=>{if(!$('tutorialOv').hidden){if(trainingStep===0&&['KeyA','KeyD','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();$('tutorialCar').style.transform=`rotate(${['KeyA','ArrowLeft'].includes(e.code)?-20:20}deg)`;$('tutorialNext').disabled=false;}else if(trainingStep===1&&e.code==='KeyI'){trainingStep=2;renderTutorial();}}});
}
function showRaceWrong(){const g=root.__bk.G,body=$('wrongBody');body.textContent='';const wrong=(g.answerLog||[]).filter(x=>!x.correct);if(!wrong.length)body.append(el('p',g.study?'本场全部答对了！':'普通模式没有答题。'));for(const x of wrong){const card=el('div',undefined,'exp-card');card.append(el('p',x.q.text),el('p','你的答案：'+x.answer),button('重新作答',()=>reviewQuestion(x.q)));body.append(card);}open('wrongOv');}
function begin(){const g=root.__bk.G;g.answerLog=[];g.lapTimes=[];g.lastLapTime=0;g.learningXP=0;g.tipSample=0;g.turnHelp=0;g.assistSign=0;g.assistElapsed=0;if(g.state==='results')progress.event('second_race');progress.event('start');g.experienceFinished=false;}
function answer(q,answer,ms){const g=root.__bk.G,correct=answer===q.answer;g.answerLog.push({q,answer,correct});progress.answer(q,correct);if(correct)g.learningXP+=10;progress.event('answer');progress.event('answer_ms',ms);if(!correct)progress.event('wrong_answer');}
function end(rank,mine,prev,bestLap,previousLap){const g=root.__bk.G;if(g.experienceFinished)return;g.experienceFinished=true;const s=progress.finish();progress.event('finish');info();const sum=$('resSummary');sum.textContent='';for(const [name,value] of [['赛车名次',`第${rank}名`],['本场最快圈',bestLap?root.__bk.fmt(bestLap):'—'],['学习经验',`+${g.learningXP+20}`]]){const card=el('div',undefined,'exp-card');card.append(el('span',name),el('b',value));sum.append(card);}if(prev!=null)$('resBest').textContent+=` · 比最佳${mine<prev?'快':'慢'} ${Math.abs(mine-prev).toFixed(2)}秒`;if(previousLap&&bestLap<previousLap)$('resBest').textContent+=' · 刷新个人最佳圈速';$('resScore').dataset.title=progress.title(s);}
async function save(body){const g=root.__bk.G;if(!g.cloudUser)return;try{queue.enqueue(g.cloudRunUser||g.cloudUser.username,body);$('saveStatus').textContent='成绩已保存本机，正在同步云端…';await flush();if(queue.read().some(x=>x.body.runId===body.runId))progress.event('save_fail');}catch{$('saveStatus').textContent='本机保存失败，请不要关闭页面，点击重试上传。';root.__bk.G.unsavedBody=body;}}
function tick(dt){const g=root.__bk?.G;if(!g||g.state!=='race'||g.paused)return;g.tipSample+=dt;if(g.tipSample<1)return;g.tipSample=0;const p=g.player;if(g.frameAvg>33)progress.event('slow_frame');const c=$('combatInfo'),parts=[];if(p.shieldT>0)parts.push(`气泡护盾 ${p.shieldT.toFixed(1)}秒`);if(p.giantT>0)parts.push(`巨型车 ${p.giantT.toFixed(1)}秒`);const target=g.order?.[g.order.indexOf(p)-1];const distance=target?Math.hypot(target.x-p.x,target.z-p.z):null;const items=[p.item,...p.itemQueue];if(items.some(x=>['missile','ice'].includes(x)))parts.push(target?`追踪目标：${target.ch.name} · ${Math.round(distance)}米${distance>200?' · 建议靠近后发射':''}`:'当前领跑 · 追踪弹向前发射');if(items.includes('lightning')||items.includes('smoke'))parts.push('闪电24米 · 烟雾18米');c.textContent=parts.join(' · ');c.hidden=!parts.length;
 const tip=$('raceTip'),tr=g.tr,a=(p.idx+20)%tr.N,b=(p.idx+50)%tr.N;let angle=tr.th[b]-tr.th[a];while(angle>Math.PI)angle-=2*Math.PI;while(angle< -Math.PI)angle+=2*Math.PI;tip.textContent=Math.abs(angle)>.4?`${angle>0?'左':'右'}弯在前方 · 提前选走线，出弯释放漂移`:g.mode==='practice'?'练习：方向 → 漂移蓄力 → 松开加速；道具保持固定格':'';tip.hidden=!tip.textContent;
}
KartExperience=root.KartExperience={weeklyGrade:grade=>applyChallenge(KartSeason.weekly(grade)),mount,begin,answer,end,save,tick,progress,queue,flush,paint(){const s=progress.read(),c=progress.cosmetics.find(c=>c.id===localStorage.getItem('bk_paint'));return c&&s.xp>=c.xp?c.color:null;},due(grade,subject){return progress.due(grade,subject);},exit(){const g=root.__bk?.G;if(g&&['race','countdown'].includes(g.state)&&!g.player?.finished)progress.event('exit');},reportQuestion};
})(globalThis);
