(()=>{
const $=id=>document.getElementById(id),api=GameAPI;
const account=GameAccount.mount({onUser:u=>window.dispatchEvent(new CustomEvent('kart-account',{detail:u}))});
$('accountBtn').onclick=()=>{$('accountOv').hidden=false;account.refresh();};
const filters=[['boardTrack','赛道',['青草环线','赤砂峡谷','雪峰回廊']],['boardDiff','难度',['休闲','标准','专业']],['boardMode','模式',['普通模式','学霸模式']],['boardGrade','年级',['一年级','二年级','三年级','四年级','五年级','六年级']],['boardSubject','题库',[]],['boardSeason','赛季',[]],['boardRaceMode','比赛类型',[]],['boardSort','排行依据',[]]];
for(const [id,name,options] of filters){const label=document.createElement('label');label.textContent=name;const select=document.createElement('select');select.id=id;select.style.cssText='display:block;width:100%;padding:8px;min-height:44px';options.forEach((text,i)=>{const o=document.createElement('option');o.value=id==='boardGrade'?i+1:i;o.textContent=text;select.append(o);});label.append(select);$('boardFilters').append(label);select.onchange=board;}
for(const [id,opts] of [['boardSeason',[[KartSeason.RULES,'当前赛季'],['kart-s2-20261002','历史1758单位赛季'],['composite-v1','历史综合分赛季'],['six-laps-v1','历史六圈赛季'],['wide-v1','历史宽赛道赛季']]],['boardRaceMode',[['race','完整比赛'],['quick','快速挑战'],['weekly','本周挑战'],['friend','当前朋友挑战']]],['boardSort',[['score','学习综合分'],['time','赛车用时']]]])for(const [value,text] of opts){const o=document.createElement('option');o.value=value;o.textContent=text;$(id).append(o);}
$('boardDiff').value='1';let sequence=0;
async function board(){const seq=++sequence;KartSubjects.populate($('boardSubject'),$('boardGrade').value);const study=$('boardMode').value==='1';$('boardGrade').disabled=$('boardSubject').disabled=!study;
 let track=$('boardTrack').value,diff=$('boardDiff').value,grade=$('boardGrade').value,subject=$('boardSubject').value,seed=0,mode=$('boardRaceMode').value;
 if(mode==='weekly'){const c=KartSeason.weekly(grade);track=c.track;diff=c.diff;subject='all';seed=c.seed;$('boardMode').value='1';$('boardTrack').value=track;$('boardDiff').value=diff;$('boardSubject').value='all';$('boardGrade').disabled=$('boardSubject').disabled=false;}
 if(mode==='friend'){const g=window.__bk?.G;if(!g||g.mode!=='friend'){$('boardStatus').textContent='先在菜单载入朋友挑战码，再查看对应榜单。';$('boardRows').textContent='';return;}track=g.trackIdx;diff=g.diff;grade=g.grade;subject=g.subject;seed=g.seed;$('boardMode').value=g.study?'1':'0';}
 const isStudy=mode==='weekly'||mode==='friend'?$('boardMode').value==='1':study;
 const params=new URLSearchParams({track,diff,study:isStudy?'1':'0',grade:isStudy?grade:'0',subject:isStudy?subject:'none',version:$('boardSeason').value,mode,seed,sort:$('boardSort').value});$('boardStatus').textContent='正在加载排行榜…';$('boardRows').textContent='';
 try{const r=await api.call('/leaderboard?'+params);if(seq!==sequence)return;const historic=$('boardSeason').value!==KartSeason.RULES;$('boardStatus').textContent=(historic?'历史成绩保留；赛道及规则与当前不同。 ':'')+(r.rows.length?($('boardSort').value==='time'?'按比赛用时排序，每人保留最快成绩。':'按综合分排序，同分按用时。每人保留最高分。'):'这个榜单还没有成绩，来争夺第一名吧！');r.rows.forEach((x,i)=>{const tr=document.createElement('tr');for(const text of [i<3?['🥇','🥈','🥉'][i]:String(i+1),x.username,x.points==null?'—':String(KartScore.fromStored(x.points)),`${(x.ms/1000).toFixed(2)}秒 · ${x.correct}/${x.total} · ${x.laps??'—'}圈 · ${x.hits??0}次`]){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('boardRows').append(tr);});}catch(e){if(seq===sequence)$('boardStatus').textContent='排行榜暂时不可用，请稍后刷新。';}}
function open(){const g=window.__bk?.G;if(g){$('boardTrack').value=g.trackIdx;$('boardDiff').value=g.diff;$('boardMode').value=g.study?'1':'0';$('boardGrade').value=g.grade;KartSubjects.populate($('boardSubject'),g.grade,g.subject);$('boardRaceMode').value=g.mode==='practice'?'quick':g.mode||'race';}$('boardOv').hidden=false;board();}
$('leaderboardBtn').onclick=open;$('refreshBoard').onclick=board;
})();
