(()=>{
const $=id=>document.getElementById(id),api=GameAPI;
const account=GameAccount.mount({onUser:u=>window.dispatchEvent(new CustomEvent('kart-account',{detail:u}))});
$('accountBtn').onclick=()=>{$('accountOv').hidden=false;account.refresh();};
const filters=[['boardTrack','赛道',['青草环线','赤砂峡谷','雪峰回廊']],['boardDiff','难度',['休闲','标准','专业']],['boardMode','模式',['普通模式','学霸模式']],['boardGrade','年级',['一年级','二年级','三年级','四年级','五年级','六年级']],['boardSubject','题库',[]]];
for(const [id,name,options] of filters){const label=document.createElement('label');label.textContent=name;const select=document.createElement('select');select.id=id;select.style.cssText='display:block;width:100%;padding:8px';options.forEach((text,i)=>{const o=document.createElement('option');o.value=id==='boardGrade'?i+1:i;o.textContent=text;select.append(o);});label.append(select);$('boardFilters').append(label);select.onchange=board;}
$('boardDiff').value='1';let sequence=0;
async function board(){const seq=++sequence;KartSubjects.populate($('boardSubject'),$('boardGrade').value);const study=$('boardMode').value==='1';$('boardGrade').disabled=$('boardSubject').disabled=!study;const params=new URLSearchParams({track:$('boardTrack').value,diff:$('boardDiff').value,study:study?'1':'0',grade:study?$('boardGrade').value:'0',subject:study?$('boardSubject').value:'none'});$('boardStatus').textContent='正在加载排行榜…';$('boardRows').textContent='';try{const r=await api.call('/leaderboard?'+params);if(seq!==sequence)return;$('boardStatus').textContent=r.rows.length?'综合分从高到低，同分按用时排序。每人保留该分类的最高分。':'这个榜单还没有成绩，来争夺第一名吧！';r.rows.forEach((x,i)=>{const tr=document.createElement('tr');for(const text of [i<3?['🥇','🥈','🥉'][i]:String(i+1),x.username,x.points==null?'—':String(KartScore.fromStored(x.points)),`${x.correct}/${x.total} · ${x.laps??6}圈 · ${x.hits??0}次`]){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('boardRows').append(tr);});}catch(e){if(seq===sequence)$('boardStatus').textContent='排行榜暂时不可用，请稍后刷新。';}}
$('leaderboardBtn').onclick=()=>{const g=window.__bk?.G;if(g){$('boardTrack').value=g.trackIdx;$('boardDiff').value=g.diff;$('boardMode').value=g.study?'1':'0';$('boardGrade').value=g.grade;KartSubjects.populate($('boardSubject'),g.grade,g.subject);}$('boardOv').hidden=false;board();};$('refreshBoard').onclick=board;
})();
