/* Display language only: canonical questions, answers and option values stay unchanged. */
var KartLanguage;
(function(root){
'use strict';
const dictionary={
 "设置": "Settings",
 "界面语言": "Interface language",
 "返回": "Back",
 "关闭": "Close",
 "方块飞车": "Block Kart",
 "← game · 游戏目录": "← Games",
 "6 台方块卡丁车 · 漂移攒火花 · 道具乱斗 · 默认6圈定胜负": "6 block karts · Drift boosts · Item battles · 6 laps by default",
 "比赛模式": "Race mode",
 "完整比赛 · 6圈": "Full race · 6 laps",
 "快速挑战 · 1圈": "Quick race · 1 lap",
 "练习模式 · 1圈": "Practice · 1 lap",
 "本周年级综合挑战 · 6圈": "Weekly grade challenge · 6 laps",
 "朋友挑战": "Friend challenge",
 "六圈完整比赛，默认模式。": "Full race, 6 laps by default.",
 "一圈练习，成绩只记本机，不进入云端排行榜。": "One practice lap. Results stay on this device.",
 "一圈快速挑战，与六圈比赛分别记录。": "One quick lap, recorded separately from full races.",
 "操作训练": "Control tutorial",
 "赛道": "Track",
 "车手": "Driver",
 "难度": "Difficulty",
 "画质": "Graphics",
 "青草环线": "Grass Circuit",
 "赤砂峡谷": "Red Canyon",
 "雪峰回廊": "Snow Pass",
 "连贯长弯 · 出弯加速": "Sweeping turns · Exit boosts",
 "连续反向弯 · 提前走线": "Alternating turns · Plan your line",
 "长短弯交替 · 控制节奏": "Mixed turns · Control your pace",
 "阿砖": "Brick",
 "蜜蜜": "Honey",
 "冰豆": "Ice Bean",
 "苔苔": "Moss",
 "炭炭": "Charcoal",
 "樱樱": "Cherry",
 "休闲": "Casual",
 "标准": "Standard",
 "专业": "Expert",
 "流畅": "Smooth",
 "均衡": "Balanced",
 "精美": "High",
 "学习学霸模式": "Learning mode",
 "学霸模式": "Learning mode",
 "年级": "Grade",
 "题库": "Question bank",
 "综合随机": "Mixed",
 "英语": "English",
 "一年级": "Grade 1",
 "二年级": "Grade 2",
 "三年级": "Grade 3",
 "四年级": "Grade 4",
 "五年级": "Grade 5",
 "六年级": "Grade 6",
 "开局驶过起跑线、每圈半圈棋盘格及终点线后答题：答对随机补满空道具格，答错不获得道具，随后继续行驶。学霸模式没有路上盲盒；答题时全场暂停。": "Answer at the start, halfway point and finish line. Correct answers fill empty item slots; incorrect answers give no items. All racers pause for questions. There are no roadside item boxes.",
 "优先抽取年级内思考题，答对直接继续比赛，答错阅读解析后点击继续。题库随年级切换；当前只开放英语；一、二年级为启蒙词汇。练习包含中文选词、听音辨词、拼写与朗读。": "Questions follow your grade. Correct answers resume the race; after an incorrect answer, read the explanation and continue. English is currently available, including beginner vocabulary for Grades 1–2. Practice covers word meanings, listening, spelling and reading aloud.",
 "背景音乐": "Music",
 "播放随机节奏音乐": "Play randomized music",
 "音乐音量": "Music volume",
 "像素冲刺 · 霓虹弯道 · 晴空飞车。比赛中随机播放，答题或暂停时音乐暂停。": "Pixel Sprint · Neon Turn · Sunny Drive. Music pauses during questions and breaks.",
 "控制设置": "Driving controls",
 "手机 / 平板转向": "Phone / tablet steering",
 "重力控制": "Tilt steering",
 "左右方向键": "Left / right buttons",
 "校准重力中心": "Calibrate tilt",
 "iPad 默认左右方向键，右下角按住加速。也可选择重力转向：左右倾斜控制方向；手机默认重力转向。无传感器时使用方向键。": "iPad defaults to direction buttons and a held accelerator. Tilt steering is also available. Phones default to tilt; without a sensor, use buttons.",
 "辅助漂移：持续转向蓄力，松开释放": "Assisted drift: hold a turn to charge, release to boost",
 "学习进度与外观": "Progress & appearance",
 "车漆（仅外观）": "Paint (appearance only)",
 "允许匿名汇总开赛、完赛、回访和保存失败次数（不含账号、答案或驾驶轨迹）": "Allow anonymous counts of starts, finishes, return visits and failed saves (no account, answers or driving traces)",
 "知识点进度": "Topic progress",
 "错题回顾": "Review mistakes",
 "本机游玩统计": "Device statistics",
 "经典原色": "Classic colors",
 "晴空蓝": "Sky blue",
 "落日橙": "Sunset orange",
 "薄荷绿": "Mint green",
 "星光紫": "Starlight purple",
 "注册 / 登录": "Register / Sign in",
 "游戏排行榜": "Leaderboard",
 "游客模式：登录后可保存云端成绩。": "Guest mode: sign in to save results online.",
 "游客可比赛，登录后保存成绩": "Guests can race. Sign in to save results.",
 "累计游玩 30 分钟后锁定 30 分钟，请合理安排休息。": "After 30 minutes of racing, take a 30-minute break.",
 "开始比赛 →": "Start race →",
 "正在加载题库…": "Loading questions…",
 "准备比赛…": "Preparing race…",
 "题库加载失败，请重试": "Could not load questions. Try again.",
 "比赛启动失败，请刷新后重试": "Could not start the race. Refresh and try again.",
 "操作说明": "How to play",
 "电脑": "Keyboard",
 "油门": "Accelerate",
 "刹车/倒车": "Brake / reverse",
 "转向": "Steer",
 "漂移": "Drift",
 "道具": "Item",
 "使用对应道具": "Use the matching slot",
 "暂停": "Pause",
 "手机/平板": "Phone / tablet",
 "手柄": "Controller",
 "漂移时间越长火花越亮：蓝 → 橙 → 紫，松开即加速。倒数到\"1\"时踩油门可起步冲刺。": "Charge drift sparks from blue to orange to purple, then release for a boost. Accelerate at countdown “1” for a start boost.",
 "自动驾驶：关": "Auto drive: Off",
 "自动驾驶：开": "Auto drive: On",
 "自动驾驶，道具和答题由你操作": "Auto drive; use items and answer questions yourself",
 "自动驾驶已开启：道具和答题由你操作": "Auto drive on: items and answers are yours",
 "已切换为手动驾驶": "Manual driving restored",
 "继续": "Resume",
 "继续比赛 →": "Continue race →",
 "继续游戏 →": "Continue game →",
 "你答错了": "Incorrect answer",
 "已跳过本题": "Question skipped",
 "本题不获得道具。": "No items awarded for this question.",
 "重新开始": "Restart",
 "返回菜单": "Main menu",
 "再来一局": "Race again",
 "声音：开": "Sound: On",
 "声音：关": "Sound: Off",
 "比赛结束": "Race finished",
 "查看排行榜": "View leaderboard",
 "起点答题": "Starting question",
 "半圈答题": "Halfway question",
 "终点答题": "Finish-line question",
 "比赛已暂停，不限答题时间。先理解条件，再作答。": "The race is paused. Take your time and answer when ready.",
 "答对随机补满空道具格；答错不获得道具，不惩罚驾驶。": "Correct answers fill empty item slots. Wrong answers give no items and no driving penalty.",
 "题目有问题": "Report question",
 "答对了！": "Correct!",
 "答错了": "Incorrect",
 "解题思路：": "Explanation:",
 "正确答案：": "Correct answer:",
 "你的答案：": "Your answer:",
 "英文拼写": "English spelling",
 "输入英文单词": "Enter the English word",
 "提交拼写": "Submit spelling",
 "▶ 播放英文": "▶ Play English audio",
 "改用中文提示": "Show meaning hint",
 "▶ 听示范发音": "▶ Hear sample pronunciation",
 "🎤 开始朗读": "🎤 Read aloud",
 "改用拼写作答": "Answer by spelling",
 "跳过本题，继续比赛（不获得道具）": "Skip question (no items)",
 "当前浏览器不支持播放，可改用文字作答。": "Audio is unavailable. You can answer in text.",
 "正在播放示范音；播放后再点击开始朗读。": "Playing a sample. Start reading aloud after playback.",
 "播放完毕，可以朗读或继续作答。": "Playback finished. Read aloud or answer.",
 "播放失败，可重试或改用文字作答。": "Playback failed. Retry or answer in text.",
 "播放未响应，请重试或改用文字作答。": "Playback timed out. Retry or answer in text.",
 "无法播放示范音，请改用文字作答。": "Sample audio is unavailable. Answer in text.",
 "正在听，请朗读目标词（最多12秒）；可随时改用拼写。": "Listening for up to 12 seconds. Read the target word or switch to spelling.",
 "未识别到内容，请重试或改用拼写。": "No speech detected. Retry or use spelling.",
 "麦克风或语音服务未获授权，可改用拼写作答。": "Microphone or speech service permission was denied. Use spelling.",
 "识别失败，请重试或改用拼写。": "Recognition failed. Retry or use spelling.",
 "未收到可判断的语音，请重试或改用拼写。": "No usable speech received. Retry or use spelling.",
 "语音识别超时，已停止麦克风；请重试或改用拼写。": "Recognition timed out and the microphone stopped. Retry or use spelling.",
 "无法启动语音识别，请改用拼写。": "Speech recognition could not start. Use spelling.",
 "点击开始朗读才使用麦克风。声音可能由浏览器语音服务处理；本站不保存录音。仅判断目标词是否被识别，不能评价口音或音素质量。": "The microphone is used only after you start. Browser speech services may process audio; this site stores no recordings. Recognition checks the target word, not accent or phoneme quality.",
 "此浏览器不支持语音识别，可听示范并改用拼写作答。": "Speech recognition is unavailable. Hear the sample and answer by spelling.",
 "识别结果：": "Recognized:",
 "中文提示：": "Meaning:",
 "请朗读：": "Read aloud:",
 "请拼写“": "Spell the English word for “",
 "”的英文单词。": "”.",
 "听一听，选出你听到的英文单词。": "Listen and choose the word you hear.",
 "护盾": "Shield",
 "烟雾": "Smoke",
 "果冻块": "Jelly",
 "追踪弹": "Homing missile",
 "气泡护盾": "Bubble shield",
 "闪电": "Lightning",
 "冰冻弹": "Ice missile",
 "弹簧跳跃": "Spring jump",
 "巨型车": "Giant kart",
 "笑脸烟雾弹": "Smiley smoke",
 "被击中！": "Hit!",
 "弹簧跳跃！腾空躲过地面陷阱": "Spring jump! Leap over ground traps",
 "巨型车！6秒内撞倒对手": "Giant kart! Knock rivals down for 6 seconds",
 "护盾：8秒内抵挡一次攻击": "Shield: blocks one attack within 8 seconds",
 "护盾挡住了攻击": "Shield blocked the attack",
 "护盾挡住了笑脸烟雾": "Shield blocked the smoke",
 "攻击被对手护盾挡住": "The rival’s shield blocked your attack",
 "中了笑脸烟雾！3秒减速": "Smiley smoke! Slowed for 3 seconds",
 "对手已避开，未计有效击倒": "Rival avoided the attack; no knockdown scored",
 "闪电24米 · 烟雾18米": "Lightning: 24 m · Smoke: 18 m",
 "当前领跑 · 追踪弹向前发射": "Leading the race · Missiles fire forward",
 "向前发射，注意没有锁定目标": "Firing forward without a locked target",
 "建议靠近后发射": "Move closer before firing",
 "注意躲避！": "Watch out!",
 "重力传感器未启用，本场使用左右方向键": "Tilt sensor unavailable; use direction buttons",
 "已校准：保持当前姿势作为转向中心": "Calibrated: keep this posture as your steering center",
 "横屏游玩视野更好": "Landscape gives a wider view",
 "冠军！": "Champion!",
 "出发！": "Go!",
 "最后一圈！": "Final lap!",
 "方向反了": "Wrong way",
 "玩家账号": "Player account",
 "账号：3–20位英文字母、数字或下划线；密码：8–128位。账号名称会出现在排行榜。": "Username: 3–20 letters, digits or underscores. Password: 8–128 characters. Your username appears on the leaderboard.",
 "账号": "Username",
 "密码": "Password",
 "例如 kart_player": "e.g. kart_player",
 "至少8位密码": "At least 8 characters",
 "登录": "Sign in",
 "注册并登录": "Register and sign in",
 "退出登录": "Sign out",
 "模式": "Mode",
 "赛季": "Season",
 "比赛类型": "Race type",
 "排行依据": "Rank by",
 "当前赛季": "Current season",
 "完整比赛": "Full race",
 "快速挑战": "Quick race",
 "本周挑战": "Weekly challenge",
 "当前朋友挑战": "Current friend challenge",
 "学习综合分": "Learning score",
 "赛车用时": "Race time",
 "刷新": "Refresh",
 "正在加载排行榜…": "Loading leaderboard…",
 "排行榜暂时不可用，请稍后刷新。": "Leaderboard unavailable. Try again later.",
 "这个榜单还没有成绩，来争夺第一名吧！": "No results yet. Be the first!",
 "休息时间": "Break time",
 "已累计游玩 30 分钟，请休息 30 分钟。": "You have raced for 30 minutes. Take a 30-minute break.",
 "倒计时结束后可以继续游戏，刷新页面仍保留锁定。": "You can resume after the countdown. Refreshing keeps the break in place.",
 "管理员解除休息": "Administrator break override",
 "管理员密码": "Administrator PIN",
 "输入管理员密码": "Enter administrator PIN",
 "解除本次休息": "End this break",
 "正在验证…": "Verifying…",
 "密码不正确，请重新输入。": "Incorrect PIN. Try again.",
 "暂时无法验证，请重试。": "Could not verify. Try again.",
 "请横屏游玩": "Rotate to landscape",
 "横屏后自动继续，答题和比赛进度会保留。": "The race will resume in landscape. Your progress is kept.",
 "横屏继续": "Continue in landscape",
 "赛车名次": "Race position",
 "本场最快圈": "Fastest lap",
 "学习经验": "Learning XP",
 "重新作答": "Try again",
 "复习作答": "Review question",
 "当前题库还没有错题。": "No mistakes for this question bank yet.",
 "本场全部答对了！": "All answers correct this race!",
 "完成答题后，这里会显示知识点进度。": "Answer questions to see your topic progress here.",
 "题目反馈": "Question feedback",
 "只提交题目编号和问题类型。": "Only the question ID and issue type are submitted.",
 "乱码或显示问题": "Unreadable text or display issue",
 "题目或答案有误": "Incorrect question or answer",
 "超出年级范围": "Beyond this grade",
 "题意不清": "Unclear question",
 "提交反馈": "Submit feedback",
 "反馈已保存，网络可用时自动提交。": "Feedback saved; it will upload when online.",
 "反馈已提交，谢谢。": "Feedback submitted. Thank you.",
 "成绩已保存本机，正在同步云端…": "Saved on this device. Syncing online…",
 "云端成绩已保存": "Results saved online",
 "本机保存失败，请不要关闭页面，点击重试上传。": "Device save failed. Keep this page open and retry.",
 "重试上传": "Retry upload",
 "本场成绩将在完成后保存到云端": "Results will save online after the race",
 "云端不可用，本场只保存本机成绩": "Online service unavailable; results stay on this device",
 "账号服务暂时不可用，本机游玩不受影响": "Account service unavailable. You can still race locally.",
 "还没有纪录": "No record yet",
 "最佳：": "Best:",
 "每个年级可选科目均不少于100道题": "At least 100 questions per available grade and subject",
 "新车手": "Rookie",
 "学习车手": "Learning racer",
 "弯道学者": "Corner scholar",
 "复习达人": "Review master",
 "原色": "Original colors",
 "樱花粉": "Cherry pink",
 "冠军金": "Champion gold",
 "空格": "Space",
 "左摇杆转向": "Left stick steering",
 "刹车": "Brake",
 "向左转": "Turn left",
 "向右转": "Turn right",
 "加速": "Accelerate",
 "圈 ": "Lap ",
 "：iPad 默认左右方向键，按住右下角加速；手机默认倾斜转向（自动油门），可切换方向键 · 左侧道具 · 右侧加速 / 刹车（道具按从左到右使用，自动跳过空格）": ": iPad: direction buttons and held accelerator. Phone: tilt steering with automatic acceleration, or switch to buttons. Items on the left; accelerator / brake on the right. Items use the first occupied slot.",
 "道具（8种等概率）：果冻块设陷阱；追踪弹攻击；护盾抵挡一次攻击（8秒）；闪电攻击24米内对手；冰冻弹击倒并减速3秒；弹簧跃起；巨型车6秒撞倒；笑脸烟雾18米范围减速3秒。": "8 equally likely items: jelly traps, homing missiles, shields, lightning, ice missiles, spring jumps, giant karts and smiley smoke.",
 "道具（8种等概率）：果冻块设陷阱；追踪弹攻击；护盾抵挡一次攻击（8秒）；闪电攻击24米内对手；冰冻弹击倒并减速3秒；弹簧跳跃腾空躲陷阱；巨型车6秒撞倒对手；笑脸烟雾18米范围减速3秒。": "8 equally likely items: jelly traps; homing missiles; shields that block one attack for 8 seconds; lightning with a 24 m range; ice missiles that slow for 3 seconds; spring jumps over traps; giant karts for 6 seconds; smiley smoke with an 18 m range for 3 seconds.",
 "仅显示最佳成绩": "Best results only",
 "当前赛季与历史分开": "Current and historic seasons are separate",
 "排名": "Rank",
 "玩家": "Player",
 "综合分": "Score",
 "用时 / 答题 / 圈数 / 击倒": "Time / Answers / Laps / Hits",
 "记录": "Result",
 "游戏内排行榜": "In-game leaderboard",
 "刷新榜单": "Refresh leaderboard",
 "历史英语单点赛季": "Historic English start/finish season",
 "历史综合学霸赛季": "Historic mixed learning season",
 "历史1758单位赛季": "Historic 1758-unit season",
 "历史综合分赛季": "Historic score season",
 "历史六圈赛季": "Historic six-lap season",
 "历史宽赛道赛季": "Historic wide-track season",
 "按比赛用时排序，每人保留最快成绩。": "Sorted by race time; each player’s fastest result.",
 "按综合分排序，同分按用时。每人保留最高分。": "Sorted by score, then time; each player’s best score.",
 "历史成绩保留；赛道及规则与当前不同。 ": "Historic results are kept; the track and rules differ. ",
 "先在菜单载入朋友挑战码，再查看对应榜单。": "Load a friend challenge from the menu to see its leaderboard.",
 "保存这个挑战码可再次挑战。": "Keep this code to play the challenge again.",
 "生成并复制挑战链接": "Create and copy challenge link",
 "载入挑战码": "Load challenge code",
 "粘贴 BK2- 开头的挑战码": "Paste a challenge code starting with BK2-",
 "已复制。": "Copied. ",
 "复制不可用，请手动复制下面的挑战码。": "Copy unavailable. Copy the challenge code manually.",
 "挑战码无效或属于旧版本。": "Invalid or outdated challenge code.",
 "挑战已载入，关闭后开始比赛。": "Challenge loaded. Close this panel to race.",
 "挑战码无效或版本已更新": "Invalid or outdated challenge code",
 " · 相同题目、赛道与随机种子": " · Matching questions, track and seed",
 "分享后，朋友使用相同赛道、难度、题目和随机种子；当前为异步比成绩。": "Share the same track, difficulty, questions and seed with friends. Results are compared asynchronously.",
 "开赛次数": "Races started",
 "完成次数": "Races finished",
 "完成率": "Finish rate",
 "连续再开一场": "Back-to-back races",
 "游玩天数": "Days played",
 "答题平均思考时间": "Average answer time",
 "保存失败次数": "Failed saves",
 "低帧率采样": "Low frame-rate samples",
 "查看全站匿名汇总": "View anonymous totals",
 "统计服务暂时不可用。": "Statistics unavailable.",
 "自愿参与统计的玩家计数；不能代表全部玩家。": "Counts from players who opted in; not all players.",
 "本机数据不代表全站。匿名汇总默认关闭，可在学习进度与外观中自愿开启。需积累玩家回访数据后再决定实时多人联机。": "Device data is not site-wide. Anonymous counts are off by default and can be enabled in Progress & appearance. Return-visit data will help evaluate real-time multiplayer.",
 "普通模式没有答题。": "No questions in standard mode.",
 "本机反馈保存失败，请检查存储空间": "Could not save feedback. Check device storage.",
 "暂时无法上传，请稍后重试。": "Upload unavailable. Try again later.",
 "本机存储空间不足，请保持页面打开后重试。": "Device storage is full. Keep this page open and retry.",
 "答对了。": "Correct. ",
 "先独立思考，再选择答案。": "Think first, then choose an answer.",
 "掌握情况仅代表本机练习记录。": "Mastery reflects practice on this device only.",
 " · 已复习": " · Reviewed",
 "连续答对，继续巩固": "Correct streak; keep practicing",
 "练习中": "Practicing",
 "每次比赛答对 +10，完成比赛 +20。复习不重复刷经验。": "Earn +10 XP per correct race answer and +20 per finish. Reviews do not add XP.",
 "刷新个人最佳圈速": "New personal best lap",
 "新纪录！": "New record!",
 "本场用时：": "Race time: ",
 "未刷新纪录": "No new record",
 "已登录：": "Signed in: ",
 " · 完赛自动保存云端成绩": " · Results save online after finishing",
 "左弯在前方 · 提前选走线，出弯释放漂移": "Left turn ahead · Choose your line and release drift on exit",
 "右弯在前方 · 提前选走线，出弯释放漂移": "Right turn ahead · Choose your line and release drift on exit",
 "练习：方向 → 漂移蓄力 → 松开加速；道具保持固定格": "Practice: steer → charge drift → release to boost. Item slots stay fixed.",
 "正在读取题库数量…": "Loading question count…",
 "比赛暂停": "Race paused",
 "自动驾驶": "Auto drive",
 "触屏转向": "Touch steering",
 "开启护盾": "Activate shield",
 "气泡护盾已开启": "Bubble shield active",
 "使用道具按钮开启护盾（按格子顺序）": "Use the item button to activate a shield (slot order)"
};
const phrases=Object.entries(dictionary).sort((a,b)=>b[0].length-a[0].length);
let language='zh';try{if(localStorage.getItem('bk_language')==='en')language='en';}catch{}
const texts=new WeakMap(),attributes=new WeakMap();let observer,selector;
function translate(source){
 if(dictionary[source])return dictionary[source];
 let out=source;
 for(const [zh,en]of phrases)if(zh.length>25||/\d/.test(zh))out=out.split(zh).join(en);
 const patterns=[
 [/“([^”]+)”对应哪个英文单词？/g,'Which English word means “$1”?'],
 [/请拼写“([^”]+)”。/g,'Spell the English word for “$1”.'],
 [/ 表示“([^”]+)”。注意字母顺序，跟读示范后再试。/g,' means “$1”. Check the letter order and try after hearing the sample.'],
 [/当前题库 (\d+) 道 · 随机选项 · 近期相似题避让/g,'$1 questions · Shuffled choices · Recent repeats avoided'],
 [/快捷键([IOP])：/g,'Key $1: '],[/空道具格，快捷键([IOP])/g,'Empty item slot, key $1'],
 [/剩余(\d+)个道具/g,'$1 items remaining'],[/第\s*(\d+)\s*圈/g,'Lap $1'],[/第\s*(\d+)\s*名/g,'Place $1'],[/(\d+)年级/g,'Grade $1'],
 [/闪电击倒 (\d+) 位对手/g,'Lightning knocked down $1 rivals'],[/笑脸烟雾影响 (\d+) 位对手/g,'Smoke affected $1 rivals'],
 [/有效击倒 /g,'Knocked down '],[/锁定 /g,'Locked on: '],[/追踪目标：/g,'Target: '],
 [/气泡护盾 ([\d.]+)秒/g,'Bubble shield: $1 s'],[/巨型车 ([\d.]+)秒/g,'Giant kart: $1 s'],
 [/（(\d+)经验解锁）/g,' (unlock at $1 XP)'],[/学习经验 (\d+) · 完成 (\d+) 场/g,'Learning XP $1 · $2 races completed'],
 [/([\d.]+)秒/g,'$1 s'],[/(\d+)米/g,'$1 m'],[/ · (\d+)圈 · (\d+)次/g,' · $1 laps · $2 hits']
 ];
 for(const [pattern,replacement]of patterns)out=out.replace(pattern,replacement);
 for(const [zh,en]of phrases)out=out.split(zh).join(en);
 return out;
}
function excluded(node){const el=node.nodeType===1?node:node.parentElement;return !el||el.closest('script,style,[data-no-translate]');}
function text(node){if(excluded(node))return;const old=texts.get(node),current=node.nodeValue;const source=old&&current===old.last?old.source:current;if(!source||(!old&&!/[\u3400-\u9fff]/.test(source)))return;const next=language==='en'?translate(source):source;texts.set(node,{source,last:next});if(next!==current)node.nodeValue=next;}
function element(el){if(excluded(el))return;
 // Explicit values keep translated labels from changing report reasons or answers.
 if(el.tagName==='OPTION'&&!el.hasAttribute('value'))el.value=el.textContent;
 let cache=attributes.get(el);if(!cache){cache={};attributes.set(el,cache);}
 for(const name of ['aria-label','title','placeholder','alt']){const current=el.getAttribute(name);if(current==null)continue;const old=cache[name],source=old&&current===old.last?old.source:current;const next=language==='en'?translate(source):source;cache[name]={source,last:next};if(next!==current)el.setAttribute(name,next);}
}
function scan(node){if(node.nodeType===3){text(node);return;}if(node.nodeType!==1||excluded(node))return;element(node);for(const child of node.childNodes)scan(child);}
function set(value){language=value==='en'?'en':'zh';try{localStorage.setItem('bk_language',language);}catch{}document.documentElement.lang=language==='en'?'en':'zh-CN';if(selector)selector.value=language;scan(document.body);document.title=language==='en'?'Block Kart | Brassivo':'方块飞车 · Block Kart | Brassivo';}
function mount(container){const label=document.createElement('label');label.className='exp-label';label.append(document.createTextNode('界面语言'));selector=document.createElement('select');selector.id='languageSelect';for(const [value,name]of [['zh','中文'],['en','English']]){const option=document.createElement('option');option.value=value;option.textContent=name;option.setAttribute('data-no-translate','');selector.append(option);}selector.value=language;selector.onchange=()=>set(selector.value);label.append(selector);container.prepend(label);}
function start(){set(language);observer=new MutationObserver(records=>{for(const r of records){if(r.type==='characterData')text(r.target);else if(r.type==='attributes')element(r.target);else for(const n of r.addedNodes)scan(n);}});observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['aria-label','title','placeholder','alt']});}
KartLanguage=root.KartLanguage={translate,set,mount,start,get:()=>language};
})(globalThis);
